### PR TITLE
Fixes #3623: Word expansion for interfaces

### LINKED ISSUE #3623: Improve interfaces templates: allow word expansion
### Environment
* Python version:  3.7
* NetBox version:  2.6.6

### Proposed Functionality
In the template interface, allow user to expand names. For example `Interface/[FRONT|BACK]/Eth[1-10]` would produce:

```
Interface/FRONT/Eth1
Interface/FRONT/Eth2
Interface/FRONT/Eth3
Interface/FRONT/Eth4
Interface/FRONT/Eth5
Interface/FRONT/Eth6
Interface/FRONT/Eth7
Interface/FRONT/Eth8
Interface/FRONT/Eth9
Interface/FRONT/Eth10
Interface/BACK/Eth1
Interface/BACK/Eth2
Interface/BACK/Eth3
Interface/BACK/Eth4
Interface/BACK/Eth5
Interface/BACK/Eth6
Interface/BACK/Eth7
Interface/BACK/Eth8
Interface/BACK/Eth9
Interface/BACK/Eth10
```

### Use Case

We need such expansion pattern for our device templates. Maybe others do as well!

### Database Changes
None

### External Dependencies
None

### PR DESCRIPTION
**Pull request by hSaria**
### Fixes: #3623 

Word expansion for interfaces. Just needed accept non-ranges as values. Also added graceful handling to ranges with more than a single character (currently throws an `ord` error because it has more than one character in a range's beginning or end).

> I could not, for the life of me, think of a better example of word expansion than `[xe,ge]-0/0/0`. I'm open for suggestions.

### CODE REVIEW

**Comment by jeremystretch** [comment]
Let's come up with a TestCase for this function (which is already overdue) before we make any further changes to it. `utilities/tests/test_forms.py` is probably where it should go. @hSaria let me know if you're interested in taking this on or if you'd prefer I handle it. I'm good either way.

**Comment by hSaria** [comment]
Sure thing! I'll follow what convention already exists for other test cases.

**Comment by jeremystretch** [comment]
@hSaria Thanks! Let me know if you run into any issues.

**Comment by hSaria** [comment]
@jeremystretch, I've added an exhaustive list of tests which should cover the possible types of input (including invalid) and the excepted output, but let me know if I missed any or if you'd like something changed.

**Pull request merged**
