### PR TITLE
#8331 Maximize browser compatibility

### LINKED ISSUE #8331: Browser compatibility to Netbox
### NetBox version

v3.1.5

### Python version

3.9

### Steps to Reproduce

Use older browser like Chrome  Version 76 or 84

- Go to Devices and select Filter
- Open a drop-down menu with dynamic content like Sites

### Expected Behavior

Within the drop-down menu all available Sites should be displayed.

### Observed Behavior

Non of the available sites are displayed. An error within the development Console is shown.

image

### PR DESCRIPTION
**Pull request by mathieu-mp**
### Fixes: #8331 - Browser compatibility to Netbox

Replace String.replaceAll with String.replace for browser compatibility issues

### CODE REVIEW

**Comment by mathieu-mp** [comment]
It is my first time with TypeScript, and I am not able to test this code.
Could someone review this PR and test the code, please ?

**Comment by thatmattlove** [comment]
Hey @mathieu-mp, I took your changes and built on them a little bit by implementing a `replaceAll` utility function to do the same thing — that way other developers don't need to remember to add the `g` flag (and there's some type checking/coercion too).

That said, I totally messed up the git process and accidentally created a new branch from your changes and merged that. So your changes are still in the commit history, but not associated with this PR. I _think_ we can just close this now, but I'll let @jeremystretch clean up my mess from here 😬 

Thanks for contributing!

**Comment by jeremystretch** [comment]
Yep, looks like @mathieu-mp's work made it in as expected, just in a slightly roundabout way. :slightly_smiling_face: Thanks both!

**Comment by mathieu-mp** [comment]
@thatmattlove: Did you get the chance to test my changes before merging to develop? I can see those changes in the commit history of develop branch. As I mentioned earlier, I did not test my code in any way as I have zero experience with TypeScript.

**Comment by thatmattlove** [comment]
@mathieu-mp I did, and what you did was perfectly fine, I just wanted to abstract it a bit. I'm also working on putting together some basic unit tests for the TS code, and I wrote [this test](https://github.com/netbox-community/netbox/blob/b0f7f8c3cfd2f00c14e8aedc0780c4fbb0fea233/netbox/project-static/src/__tests__/util.test.ts#L343-L376) for the new `replaceAll` utility, which passes.

**Pull request closed without merging**
