### PR TITLE
SAML Authentication

### LINKED ISSUE #1677: SAML Authentication
### Issue type
[ x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description

My employer is currently going through a large push to use SAML for application authentication. As such, I would like to implement SAML for netbox. I have several django projects similar to (and sometimes based on the core of) netbox which I am currently working on SAML integration, so it would be rather trivial to contribute it back.

This was first brought up in #118 but I also agree with the decision to close that issue for being too broad and under defined. This request covers _only_ the addition of SAML support for authentication and no other use case.

Let me be clear in saying this is something I am 100% willing to do the work on myself. 

I see it looking very similar to the LDAP support, in that it is a bolt on that a user must enable themselves. This would most likely be using [djangosaml2](https://github.com/knaperek/djangosaml2)

### PR DESCRIPTION
**Pull request by anthonyeden**
### Fixes: #1677 

This pull request begins work on including SAML2 Authentication support in NetBox. It relies on the mature project fangli/django-saml2-auth to do the heavy lifting, and includes as few as possible changes to NetBox itself.

I'm submitting this as a draft PR for now so any interested parties can see my progress thus far. However, further work is needed before merging this into the NetBox project. For example, I need to add support for group mapping.

Feedback is welcomed.

### CODE REVIEW

**Comment by ksofa2** [comment]
I'm not going to have time to test this right now, but I think it looks great. Thanks for working on this!

**Comment by jessiebryan** [comment]
@anthonyeden - I am trying to test your work against OneLogin idP - I am troubleshooting some issues. 

Can you clarify if "LOGIN_REQUIRED = False" (netbox/configuration.py) is needed for the saml2_auth/acs/ to get consumed?

I am using Ubuntu 16LTS for this environment

**Comment by rje6459** [comment]
@anthonyeden, this question may stem from my ignorance of the [fangli/django-saml2-auth](https://github.com/fangli/django-saml2-auth) package, but is SP metadata generation done automatically?

**Comment by anthonyeden** [comment]
@jessiebryan The value 'LOGIN_REQUIRED' doesn't alter the behaviour of this change, in my Ubuntu 18LTS environment. What issues are you encountering?

**Comment by anthonyeden** [comment]
@rje6459 In my test environment with Okta, I have taken the IDP Metadata provided by Okta, saved it in a file, and referenced this file in config field 'METADATA_LOCAL_FILE_PATH'. I have not had to generate anything from the Django/Netbox side of things - just populate the saml_config.py file as described in the documentation.

**Comment by anthonyeden** [comment]
Hi everyone,

I've done a lot of testing, and have this working happily with Okta as the identity provider. I have a more detailed instructional setup guide for Okta (with screenshots), which I will post somewhere soon.

The only bug I've encountered since the initial pull request has been fixed in 6c6eb6f. I'm not 100% sure if this is the most elegant solution, but I was struggling to think of a better way to handle this corner case when it flushes the existing sessions, and asserts because the session doesn't exist.

Happy to have further discussion surrounding this.

**Comment by BenoitKnecht** [comment]
@anthonyeden I've been testing your PR as well, but using Azure ADFS, and it works well. I've made a couple of changes to customize the login screen and avoid a redirect loop when `LOGIN_REQUIRED=True`: a9fcd5217adde46f807cb009a38bb533455f7707; feel free to cherry-pick what you deem useful.

**Comment by BenoitKnecht** [comment]
BTW, one thing I didn't manage to get working is redirection to the `?next=` path after login. The issue is that django-saml2-auth stores the `next` URL in your session, then redirects you to your SAML provider, which redirects you back to Netbox after login.

But since the session cookie has `SameSite=Lax`, it isn't presented to Netbox after that last redirect, so a new session is created and the `next` URL is lost.

I don't know if you've noticed the same behavior, and if there's a simple solution I'm not thinking of. It's not a blocking issue of course, but it would be nice to get it working.

**Comment by anthonyeden** [comment]
Cool, thanks @BenoitKnecht! I'll have a bit of a play, and hopefully merge it in.

**Comment by rje6459** [comment]
@anthonyeden, thank you for clarification that the `METADATA_LOCAL_FILE_PATH` variable is for the IdP metadata. It appears that in when setting up a SAML application in Okta, that the information you're entering is creating the SP metadata on Okta's side. This can be seen in step 6 on the [Setting Up a SAML Application in Okta](https://developer.okta.com/standards/SAML/setting_up_a_saml_application_in_okta/) page.

Not all IdPs will have a page like this to generate the SP metadata information. Many applications that natively support SAML will also do the metadata generation at its own `/saml/metadata/` endpoint, facilitating the ability to have `validUntil` and `cacheDuration` attributes for the metadata.

I'm also not seeing on the Okta page where the SP's x509 certificate(s) for signing and encryption are included; perhaps that will be enlightened with your advanced configuration instructions.

**Comment by BenoitKnecht** [comment]
@anthonyeden I realized there were a couple of typos in the commit I mentioned; I had fixed them in https://github.com/BenoitKnecht/netbox/tree/dev, but that branch also contains a bunch of unrelated changes to simplify running Netbox on Kubernetes.

So to make things easier, I rebased a branch on your `anthonyeden:dev_saml` branch and included only the commit related to SAML: https://github.com/BenoitKnecht/netbox/tree/saml. I'll keep it up to date if I notice other issues.

**Comment by jessiebryan** [comment]
> @jessiebryan The value 'LOGIN_REQUIRED' doesn't alter the behaviour of this change, in my Ubuntu 18LTS environment. What issues are you encountering?

Thanks @anthonyeden - with `LOGIN_REQUIRED=False` I am getting a python traceback:


AttributeError at /saml2_auth/acs/


     'NoneType' object has no attribute 'require_signature'

     Request Method: POST

     Request URL:    https://nb.example.net/saml2_auth/acs/

     Django Version: 2.1.8

     Exception Type: AttributeError

     Exception Value:    'NoneType' object has no attribute 'require_signature'

     Exception Location: /usr/local/lib/python3.6/dist-packages/saml2/entity.py in _parse_response, line 1213

     Python Executable:  /usr/bin/python3

     Python Version: 3.6.7

     Python Path:    ['/opt/netbox/netbox',
                               '/usr/local/bin',
                               '/usr/lib/python36.zip',
                               '/usr/lib/python3.6',
                               '/usr/lib/python3.6/lib-dynload',
                               '/usr/local/lib/python3.6/dist-packages',
                               '/usr/lib/python3/dist-packages']



I'm not using Okta though - I use OneLogin. I found [this](https://github.com/IdentityPython/pysaml2/issues/598#issuecomment-493227980) issue related to the 'require_signature' problem - but It's way over my head. 

Anyone have ideas on this?

**Comment by rje6459** [comment]
@anthonyeden, I'm testing your PR but I'm having a difficult time with getting the attributes mapped correctly. I'm using a Shibboleth IdP with the following attribute definitions:

```xml
    <resolver:AttributeDefinition id="mail" xsi:type="ad:Simple" 
        xmlns="urn:mace:shibboleth:2.0:resolver:ad" sourceAttributeID="mail">
        <resolver:Dependency ref="ritLDAP" />
        <resolver:AttributeEncoder xsi:type="enc:SAML1String" name="urn:mace:dir:attribute-def:mail" encodeType="false" />
        <resolver:AttributeEncoder xsi:type="enc:SAML2String" name="urn:oid:0.9.2342.19200300.100.1.3" friendlyName="mail" encodeType="false" />
    </resolver:AttributeDefinition>

    <resolver:AttributeDefinition id="uid" xsi:type="ad:Simple" 
        xmlns="urn:mace:shibboleth:2.0:resolver:ad" sourceAttributeID="uid">
        <resolver:Dependency ref="ritLDAP" />
        <resolver:AttributeEncoder xsi:type="enc:SAML1String" name="urn:mace:dir:attribute-def:uid" encodeType="false" />
        <resolver:AttributeEncoder xsi:type="enc:SAML2String" name="urn:oid:0.9.2342.19200300.100.1.1" friendlyName="uid" encodeType="false" />
    </resolver:AttributeDefinition>

    <resolver:AttributeDefinition id="cn" xsi:type="ad:Simple" 
        xmlns="urn:mace:shibboleth:2.0:resolver:ad" sourceAttributeID="cn">
        <resolver:Dependency ref="ritLDAP" />
        <resolver:AttributeEncoder xsi:type="enc:SAML1String" name="urn:mace:dir:attribute-def:cn" encodeType="false" />
        <resolver:AttributeEncoder xsi:type="enc:SAML2String" name="urn:oid:2.5.4.3" friendlyName="cn" encodeType="false" />
    </resolver:AttributeDefinition>

    <resolver:AttributeDefinition id="sn" xsi:type="ad:Simple" 
        xmlns="urn:mace:shibboleth:2.0:resolver:ad" sourceAttributeID="sn">
        <resolver:Dependency ref="ritLDAP" />
        <resolver:DisplayName xml:lang="en">Last Name</resolver:DisplayName>
        <resolver:AttributeEncoder xsi:type="enc:SAML1String" name="urn:mace:dir:attribute-def:sn" encodeType="false" />
        <resolver:AttributeEncoder xsi:type="enc:SAML2String" name="urn:oid:2.5.4.4" friendlyName="sn" encodeType="false" />
    </resolver:AttributeDefinition>

```

And this is what my `saml_config.py` looks like:
```python
SAML2_AUTH = {
    # Metadata is required. Specify either a remote url or local file path
    'METADATA_AUTO_CONF_URL': 'https://shibboleth-test.main.ad.rit.edu/idp/shibboleth',

    # Optional settings below
    'CREATE_USER': 'TRUE', # Create a new Django/NetBox user when a new user logs in. Defaults to True.
    'NEW_USER_PROFILE': {
        'USER_GROUPS': [],  # The default group name when a new user logs in
        'ACTIVE_STATUS': True,  # The default active status for new users
        'STAFF_STATUS': True,  # The staff status for new users
        'SUPERUSER_STATUS': False,  # The superuser status for new users
    },
    'ATTRIBUTES_MAP': {  # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
        'email': 'mail',
        'username': 'uid',
        'first_name': 'cn',
        'last_name': 'sn',
    },
    'ENTITY_ID': 'https://cac-docker.rit.edu/saml2_auth/acs/', # Populates the Issuer element in authn request
}
```

Is django_saml2_auth expecting the friendlyName, name, or some other attribute?

**Comment by aficustree** [comment]
Just sharing that this seems to be working great with Azure AD....is there a way in the attribute map to accept a group name as a claim and place the user into that group?

**Comment by anthonyeden** [comment]
Hi @aficustree,

I've got a pull request django_saml2_auth which supports groups. See here: https://github.com/fangli/django-saml2-auth/pull/102

So far, I've only tested this with Okta groups. Okta simple supplies a list of groups as a attribute.

**Comment by aficustree** [comment]
@anthonyeden , that's quite slick. Azure AD seems to have the concept of user defined 'roles' but you have to manage them from a JSON in Azure AD. It doesn't seem to be able to pass group membership via security group. Given managing a custom field in a JSON in Azure AD is more work than just dumping everyone into read-only and manually uplifting, might as well just do that instead....I'll look to try it out if Azure AD ever ups its game

**Comment by aficustree** [comment]
@anthonyeden I managed to get this working with groups and then I went to rebuild it for readiness to prod and now seem to get this error. Any earthly idea? I'm sure it's easy 

```
netbox_1         |   File "/opt/netbox/netbox/netbox/urls.py", line 74, in <module>
netbox_1         |     url(r'^saml2_auth/', include('django_saml2_auth.urls')),
netbox_1         | NameError: name 'url' is not defined
```

things seem properly installed 

```
bash-4.4# pip list | grep -i django-saml2-auth
django-saml2-auth        2.2.1
```

**Comment by aficustree** [comment]
never mind, looks like upstream removed url from the includes in `url.py` , added it back, leaving here in case anyone runs into the same

**Comment by lukasodhner** [comment]
Looking forward to this.  Thanks for your work.

**Comment by bootc** [comment]
@anthonyeden do you think you'll have a chance to rebase this against a newer version of NetBox? I'd really like to see this merged. Let me know if I can help.

**Comment by dhoer** [comment]
Hey @jeremystretch, is it possible for you or someone else on your team to take a serious look at this PR?  Thanks in advance

**Comment by jeremystretch** [comment]
In order to be merged, this needs:

* Rebasing against the current `develop` branch
* Thorough testing and confirmation of intended behavior from multiple users
* Someone to own SAML authentication long-term

We made the mistake of merging LDAP authentication before it was really ready and ended with numerous bugs and no one to own them.

**Comment by jeremystretch** [comment]
After some discussion, we've decided to scratch the adoption of SAML as it (along with LDAP) imposes a significant maintenance burden for something that isn't central to NetBox's purpose. Instead, we'll work on adopting the ability to infer authentication established via the HTTP frontend (see #2328) as it allows much more flexibility.

Thank you for your work, and my apologies for not addressing this sooner.

**Pull request closed without merging**
