### PR TITLE
Upgrade to Django 3.1 (v2.9)

### PR DESCRIPTION
**Pull request by jeremystretch**
This is a draft PR to track the work necessary for upgrading to Django 3.1. Most issues have been addressed, however there remains a bug regarding queryset ordering when annotations are used. This was called out as [an intentional change in Django 2.2](https://docs.djangoproject.com/en/3.1/releases/2.2/#model-meta-ordering-will-no-longer-affect-group-by-queries), however I'm not sure we have a reasonable workaround (further comments below).

### CODE REVIEW

**Comment by jeremystretch** [comment]
Under Django 3.1, a model's `Meta.ordering` is ignored when a `GROUP BY` SQL clause is in use. This means, for example, that

```python
DeviceType.objects.prefetch_related('manufacturer')
```

will order correctly, but

```python
DeviceType.objects.prefetch_related('manufacturer').annotate(instance_count=Count('instances'))
```

will be unordered.

**Comment by jeremystretch** [comment]
Here are the resulting SQL queries for `DeviceType.objects.prefetch_related('manufacturer').annotate(instance_count=Count('instances'))`:

```python
# Django 3.0.8
SELECT ••• FROM "dcim_devicetype"
    LEFT OUTER JOIN "dcim_device" ON ("dcim_devicetype"."id" = "dcim_device"."device_type_id")
    INNER JOIN "dcim_manufacturer" ON ("dcim_devicetype"."manufacturer_id" = "dcim_manufacturer"."id")
    GROUP BY "dcim_devicetype"."id", "dcim_manufacturer"."name"
    ORDER BY "dcim_manufacturer"."name" ASC, "dcim_devicetype"."model" ASC

# Django 3.1b1
SELECT ••• FROM "dcim_devicetype"
    LEFT OUTER JOIN "dcim_device" ON ("dcim_devicetype"."id" = "dcim_device"."device_type_id")
    INNER JOIN "dcim_manufacturer" ON ("dcim_devicetype"."manufacturer_id" = "dcim_manufacturer"."id")
    GROUP BY "dcim_devicetype"."id", "dcim_manufacturer"."name"
```

**Comment by jeremystretch** [comment]
Some rough benchmarking suggests that moving from `Count()` to [subqueries](https://github.com/netbox-community/netbox/blob/develop/netbox/utilities/utils.py#L67) may actually be the way to go:

```Provider.objects.annotate(count_circuits=Count('circuits'))```
~ 120msec, no ordering

```Provider.objects.annotate(count_circuits=get_subquery(Circuit, 'provider'))```
~ 50msec, preserved ordering

I'm not 100% confident in this assumption yet though; need to do some more testing. It would be nice to standardize on the way we annotate related object counts project-wide, though.

**Comment by lampwins** [comment]
The issue we have hit with subqueries for counting aggregates is cacheops doesn't support them for invalidation. There is some discussion on this in https://github.com/netbox-community/netbox/issues/3672

**Comment by jeremystretch** [comment]
I've opened Suor/django-cacheops#365 to see if we can get an idea how feasible this would be to work around.

**Comment by jeremystretch** [comment]
Given that we cannot immediately accommodate the use of subqueries, I've opened and implemented #4871 to manually specify ordering on the affected querysets. Eventually, this will be removed, but it is necessary now to allow moving to Django 3.1 for the v2.9 release.

**Pull request merged**
