### PR TITLE
Add icons to panel headers

### PR DESCRIPTION
**Pull request by bellwood**
Adds icons to panel headers in info, inventory and LLDP views

@jeremystretch I'll likely chat with you in IRC about adding icons per item in some of these panels (device site, rack, position)... It might be overkill

### CODE REVIEW

**Comment by jeremystretch** [comment]
I like it, but I'm worried that adding icons to all the panels on the device page will only make it seem like icons are missing from all the other pages. And we have a limited set to work with, which doesn't include appropriate icons for niche abstractions like prefixes or VLANs.

**Comment by bellwood** [comment]
I plan to hit all the panel headers to keep things consistent. I'm also working on getting us some webfonts to handle the niche stuff... Feel free to keep this PR on hold until I at least get the balance of the headers taken care of... I can make a different PR for icon enhancement once I get that wrapped

**Comment by Gelob** [comment]
@bellwood I would look into squashing and rebasing your commits as well as making use of the amend feature so that you don't have 30 commits

**Comment by bellwood** [comment]
@gelob full disclosure i'm kind of a github "n00b"... I will definitely check into it, thanks =)

**Comment by bellwood** [comment]
@jeremystretch this should have full coverage... I used my best judgement for niche items and documented what icons I used where to help ensure consistency

im sure some edits will be needed (tag I'm it)

ill move forward with outlining additional icons for better fit on niche items based on our discussion in IRC

**Comment by bellwood** [comment]
looks like the conflict is on netbox/templates/circuits/provider_list.html

ive added icons to the headers on this page

**Comment by jeremystretch** [comment]
Closing due to inactivity

**Pull request closed without merging**
