### PR TITLE
Switch to pycodestyle

### LINKED ISSUE #2124: Update pep8 references to pycodestyle in CI builds
### Issue type
[ ] Feature request 
[ x ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5
* NetBox version:  2.3

### Description
The pep8 utility has been renamed to pycodestyle and we should update the CI script and travis build to use it as pep8 will be removed in the future.
```
52.17s$ ./scripts/cibuild.sh
2018-05-29 04:42:40 | starting build checks.
/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pep8.py:2124: UserWarning: 
pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.
$ pip install pycodestyle
$ pycodestyle ...
  '\n\n'
```

### PR DESCRIPTION
**Pull request by abeutot**

### CODE REVIEW

**Comment by jeremystretch** [comment]
Changing regex strings needs to be a different PR, and an explanation is needed for each of the ignored errors.

**Comment by abeutot** [comment]
Hello Jeremy,

There are no regex value changes since the escaped sequences were invalid. Since these changes are directly caused by the switch to pycodestyle, why do you need it to be in another PR?

There is already an explanation for the ignored errors: those are the default set of ignored errors for pycodestyle. 
cf http://pycodestyle.pycqa.org/en/latest/intro.html#configuration
"In the default configuration, the checks E121, E123, E126, E133, E226, E241, E242, E704, W503, W504 and W505 are ignored because they are not rules unanimously accepted, and PEP 8 does not enforce them. Please note that if the option –ignore=errors is used, the default configuration will be overridden and ignore only the check(s) you skip."

**Comment by jeremystretch** [comment]
> There is already an explanation for the ignored errors: those are the default set of ignored errors for pycodestyle.

If that's the default configuration, there's no need to explicitly disable the checks. Any check which we decide to ignore needs to be accompanied by a justification for doing so (like E501 in the current code).

**Comment by abeutot** [comment]
Yes, there is a need to explicitly disable the checks:

"Please note that if the option –ignore=errors is used, the default configuration will be overridden and ignore only the check(s) you skip."

You want me to justify the default pycodestyle check set?

**Comment by jeremystretch** [comment]
Again, any deviation from the default configuration (e.g. any argument passed to the executable) needs to be documented. I understand that some of these warnings are disabled automatically if **no** arguments are passed. But because we _are_ passing arguments, and explicitly disabling them, we need to annotate why.

Incidentally, many of the arguments you've opted to copy from the default implementation need not be included. This is one of the reasons for documenting each suppressed warning. We should only suppress warnings which need to be suppressed.

Assuming the code is modified to comply with W605 and E722, only E501 and W504 need to be suppressed. If you want to tweak `cibuild.sh` to only include E501 and W504 (adding a comment for W504), I'll merge the PR.

**Comment by abeutot** [comment]
Here you go.

**Pull request merged**
