### PR TITLE
convert customfield multiobject to ids at save()

### LINKED ISSUE #10241: CustomField MultiObject returns dict but expects id's
### NetBox version

v3.2.9

### Python version

3.9

### Steps to Reproduce

1. Create a custom field of the multiobject type
2. create a device that uses that custom field and populate with some data
3. retrieve the custom field through the API
4. update the custom field with a new ID
5. save the device

### Expected Behavior

The device with customs fields is updated with the new value's

### Observed Behavior

The save of the object fails with the message that a dict is not acceptable, only ID's are allowed

This is because
- the GET API returns the multiobject custom fields as an array of dicts.
- the POST API expects only ID's and not dicts

Reason:
API GET call returns the expanded dicts for custom_fields multiobjects
when adding a new object to the custom_fields, we use the ID of the object
This causes the custom_fields to be a mix of dict and id's
But the deserializer of the CustomField class expects only ID's

### PR DESCRIPTION
**Pull request by PieterL75**
### Fixes: #10241 CustomField MultiObject API returns dict at read but expects id's at save

This change will convert the mixed array of dict and id's into id's only at deserialize

### CODE REVIEW

**Comment by jeremystretch** [comment]
While I agree with the approach, I don't think `serialize()` is the best place to implement it. The `serialize()` and `deserialize()` methods are core methods on CustomField, entirely decoupled from the REST API, and they should be symmetric.

As this change relates specifically to the REST API, the logic should probably go in the [`to_internal_value()`](https://github.com/netbox-community/netbox/blob/669e86f96e5866124db04e7efc1542b84966987a/netbox/extras/api/customfields.py#L65) method of `CustomFieldsDataField`.

**Comment by PieterL75** [comment]
Looks like that the to_internal_value() does not know about the customfield type. 
so I'll have to query the db for the types, itterate over all customefields and change dicts to ids...

or do you see a better approach ?

(I hope you're not spending more time in explaining me, then self fixing it.. )

**Comment by jeremystretch** [comment]
> so I'll have to query the db for the types, itterate over all customefields and change dicts to ids... or do you see a better approach ?

That's what I'm thinking. I'm sure there's probably a more elegant way to tackle it, but I'd have to go digging pretty deeply into DRF again to see what our other options might be. Open to any other ideas.

**Comment by PieterL75** [comment]
After committing.. I thought that his might be even better : 
Keep the login in the deserialize function of the model, and call that deserialize in the to_internal_value.
Similar to that is done in the to_presentation calling the serialize function

Let me know what you prefer.

**Comment by jeremystretch** [comment]
Considering this further, the related objects should be mapped using [`WritableNestedSerializer`](https://github.com/netbox-community/netbox/blob/d1efbf662005aeed91fa21fa26e34de3e307bb50/netbox/netbox/api/serializers/nested.py#L15), to ensure we provide the same functionality as is provided for built-in relationships. We can probably pass the custom field's object type to `get_serializer_for_model()` to accomplish this dynamically. Let me play with it for a bit.

**Comment by jeremystretch** [comment]
I've come up with a solution in https://github.com/netbox-community/netbox/commit/d5538c1ca3d7ef7ca2d457ce22bbc645b8b65505 per my comment above. I believe this satisfies #10241 but please let me know if you find any further limitations. Thanks!

**Pull request closed without merging**
