### PR TITLE
Add example using nginx + uwsgi

### LINKED ISSUE #1335: Document installation using uwsgi as application host
### Issue type: documentation

**Python version:**
**NetBox version:**

Running netbox under anything other than gunicorn is currently undocumented.  I've added simple steps to the web-server.md for using uwsgi as the app host instead & will include the pull request below.

I've currently kept it separate, though there's grounds to potentially merge the nginx configuration bits with the current nginx setup as essentially all that changes is which proxy function to use.

The setup is identical to the gunicorn example; nginx loads the static files and uwsgi takes the dynamic parts; I've also left out advanced config like high availability and caching as an exercise for the reader.

### PR DESCRIPTION
**Pull request by hawko2600**
Supplemental instructions on using uwsgi as the app host.

### CODE REVIEW

**Comment by jeremystretch** [comment]
Please see my comment on #1335.

**Comment by mhite** [comment]
For what it is worth, I managed to stumble across this PR after a many hour exercise in frustration getting the Debian-shipped gunicorn to play nicely with a netbox running in a virtualenv. Using the Debian-shipped gunicorn has the benefit of playing nicely with systemd with no need to mess with supervisor and integrating that into systemd.

After spinning my wheels on that for a while, I gave up and started looking in to how to setup netbox with uwsgi. Luckily I had no issue with the provided example and was able to use the Debian provided uwsgi + uwsgi-plugin-python packages along with my virtualenv configuration.

```
[uwsgi]
chdir = /opt/netbox/netbox
wsgi-file = netbox/wsgi.py
master = true
processes = 4
threads = 2
uid = www-data
socket = /run/uwsgi/netbox.sock
chown-socket = www-data:www-data
chmod-socket = 660
vacuum = true
virtualenv=/opt/virtualenv-netbox/
```
Thanks for submitting this, even if the PR was not merged. I found the bread crumb itself useful my friend!

**Comment by mhite** [comment]
BTW, I'm using `fpm`'s virtualenv feature to convert the requirements.txt into a Debian package itself. Much of this journey is trying to package and distribute netbox in sysadmin friendly manner... which presents its own set of problems! :)

**Comment by mdaviesnz** [comment]
I've been tangling with python and supervisor and messed up requirements/dependencies for a while and this option works a lot better for me (in Ubuntu 16.04.3).

**Comment by darthmdh** [comment]
I've dropped this into https://gist.github.com/darthmdh/8f0a8e05ccb5c1c8eb7641df55121c9e so it can live on forever [1]

[1] for values of "forever" where "github pay the power bill" == 1

**Pull request closed without merging**
