### PR TITLE
Fix Primary IP Sorting Issues for Devices and VMs

### LINKED ISSUE #5819: Unable to sort VMs by primary_ip
### Environment
* Python version: 3.6.8
* NetBox version: 2.10.4

### Steps to Reproduce
1. Sort virtual machines by IP Address
https://[address]/virtualization/virtual-machines/?sort=primary_ip

### Expected Behavior
VMs to be sorted.

### Observed Behavior
Application crash.

```
<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'primary_ip' into field. Choices are: cluster, cluster_id, comments, created, custom_field_data, disk, id, interfaces, last_updated, local_context_data, memory, name, platform, platform_id, primary_ip4, primary_ip4_id, primary_ip6, primary_ip6_id, role, role_id, secrets, services, status, tagged_items, tags, tenant, tenant_id, vcpus

Python version: 3.6.8
NetBox version: 2.10.4
```

Same bug as #5597

### PR DESCRIPTION
**Pull request by stuntguy3000**
### Fixes: #5819, #5872

Enables ordering by IPv6, followed by IPv4.
Ensures the displayed IP address is IPv6 or IPv4 based on the configuration.

### CODE REVIEW

**Comment by jeremystretch** [comment]
This does not respect the `PREFER_IPV4` configuration parameter.

**Comment by stuntguy3000** [comment]
> This does not respect the `PREFER_IPV4` configuration parameter.

That's fine, I can look into it, but can you (@jeremystretch) confirm if your fix for the other issue (https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/tables/devices.py#L132) is also incorrect and does not respect this configuration value?

**Comment by jeremystretch** [comment]
@stuntguy3000 yes, that needs to be fixed as well.

**Comment by stuntguy3000** [comment]
Okay ignore all that, both issues merged and fixed @jeremystretch.

**Pull request merged**
