### PR TITLE
Fix #235: Enable global vlan

### LINKED ISSUE #235: Global VLAN
HI Guys,

We use a VLAN for mgmt which spans multiple sites, rather than adding the same VLAN and making it site specific which we would do 99% of the time, can we have an option in site to be global which would automatically apply across all sites, so we only have to add it once?

Thanks
Shaun

### PR DESCRIPTION
**Pull request by peng-shawn**
1. Decouple site/vlan, make site optional for vlan/vlangroup
2. Change html generation code to check site existence before
dereference
3. Create site search function, if site is None for a VLAN, view it as
global VLAN

### CODE REVIEW

**Comment by Shawn0720** [comment]
This diff is created to resolve https://github.com/digitalocean/netbox/issues/235.

I'm open for suggestions.

**Comment by hackman61** [comment]
Hello @Shawn0720 , I'm interested by your merge, do you know why it hasn't been validated ?

**Comment by hackman61** [comment]
Hello @Shawn0720 , I'm interested by your merge, do you know why it hasn't been validated ?

**Comment by Shawn0720** [comment]
Hi, @hackman61 ! I haven't received any comment on this pull request yet.

**Comment by drybjed** [comment]
@Shawn0720 You should rebase your PR on latest changes in the `develop` branch and update this PR, basically with these steps:

1. `git checkout develop`
2. `git pull`
3. `git checkout global-vlan`
4. `git rebase develop`
5. Fix any merge conflicts, `git add` and `git rebase --continue` afterwards.
6. Publish updated PR woth `git push --force origin global-vlan`

This should fix the merge conflics and make the PR eligible again.

I'm counting on your PR. 👍

**Comment by Shawn0720** [comment]
Opening a new pull request to have a cleaner diff.

**Pull request closed without merging**
