### PR TITLE
Closes #2487: Enable brief API output utilizing nested serializers

### LINKED ISSUE #2487: Enable abbreviated API responses e.g. for populating form fields
### Environment
* Python version:  3.5.2
* NetBox version: 2.4.5

### Proposed Functionality
Enable abbreviated output when a particular parameter (e.g. `?brief=1`) is passed with an API request. For example, `GET /api/dcim/devices/` returns a full representation of each device in the list, `GET /api/dcim/devices/?brief=1` would return only the integer ID and a text representation of each device.

### Use Case
The REST API uses serializers to return NetBox resources as JSON objects. The API output includes all resource attributes, and often includes nested representation of related resources. This can be inefficient when the API output is used for tasks where only a basic representation of each object is required; for example, when populating a `<select>` widget within an HTML form.

### Database Changes
None

### External Dependencies
None

### PR DESCRIPTION
**Pull request by jeremystretch**
### Fixes: #2487

Minimize API output when `?brief` is passed as a query parameter.

### CODE REVIEW

**Comment by lampwins** [comment]
While not required by the RFC, I have never been a fan of valueless query params as they can sometimes be annoying to dealwith on the client side. That said, this use case _should_ be fine. Otherwise this looks good to me!

**Comment by lampwins** [comment]
I might sugest a test for this though.

**Comment by jeremystretch** [comment]
@lampwins Fair point. Should we look for `params['brief'] == True`? And yeah, I'll add a test if you're good with the overall approach.

**Comment by lampwins** [comment]
@jeremystretch Yeah, I think `if request.query_params.get('brief', False)` should do the trick. I can't think of any other better way to get to the Nested serializer, especially since we already have `get_serializer_for_model()`, so this looks good.

**Pull request merged**
