### PR TITLE
Some additional fixes to scripts/reports background running (2.9)

### PR DESCRIPTION
**Pull request by glennmatthews**
### Fixes: #2006 

Follow-up to #4799. Fixes two issues:

1) `success` log result was misspelled as `sucess`, which was causing display issues in the result detail view (since `label-sucess` (sic) is not a defined Bootstrap style).
2) If a script was run with `commit=False`, its JobResult status would remain as `running` indefinitely even after the script execution had actually completed.

### CODE REVIEW

**Comment by lampwins** [comment]
I am fine with this, but I wonder if we could refactor the script execution logic to avoid nested try blocks.

**Comment by glennmatthews** [comment]
I'm open to suggestions on the refactoring. I *think* the following alternative would work but I personally think it's less readable:

```python
    try:
        with transaction.atomic():
            script.output = script.run(**kwargs)

            if not commit:
                raise AbortTransaction()

    except AbortTransaction:
        job_result.data = ScriptOutputSerializer(script).data
        job_result.set_status(JobResultStatusChoices.STATUS_COMPLETED)

    except Exception as e:
        stacktrace = traceback.format_exc()
        script.log_failure(
            "An exception occurred: `{}: {}`\n```\n{}\n```".format(type(e).__name__, e, stacktrace)
        )
        logger.error(f"Exception raised during script execution: {e}")
        commit = False
        job_result.set_status(JobResultStatusChoices.STATUS_ERRORED)

    else:
        job_result.data = ScriptOutputSerializer(script).data
        job_result.set_status(JobResultStatusChoices.STATUS_COMPLETED)

    finally:
        if not commit:
            # Delete all pending changelog entries
            purge_changelog.send(Script)
            script.log_info(
                "Database changes have been reverted automatically."
            )
```

**Comment by glennmatthews** [comment]
Or a second option:

```python
    try:
        with transaction.atomic():
            script.output = script.run(**kwargs)

            if not commit:
                raise AbortTransaction()

    except AbortTransaction:
        pass

    except Exception as e:
        stacktrace = traceback.format_exc()
        script.log_failure(
            "An exception occurred: `{}: {}`\n```\n{}\n```".format(type(e).__name__, e, stacktrace)
        )
        logger.error(f"Exception raised during script execution: {e}")
        commit = False
        job_result.set_status(JobResultStatusChoices.STATUS_ERRORED)

    finally:
        if job_result.status != JobResultStatusChoices.STATUS_ERRORED:
            job_result.data = ScriptOutputSerializer(script).data
            job_result.set_status(JobResultStatusChoices.STATUS_COMPLETED)

        if not commit:
            # Delete all pending changelog entries
            purge_changelog.send(Script)
            script.log_info(
                "Database changes have been reverted automatically."
            )
```

**Comment by jeremystretch** [comment]
I think [this approach](https://github.com/netbox-community/netbox/pull/4852#issuecomment-658391818) is fine. It might be cleaner to only set `STATUS_COMPLETED` if no status has been set, but either way.

**Comment by glennmatthews** [comment]
The status is set to `STATUS_RUNNING` at the start of the function - I could change the `status != STATUS_ERRORED` check to `status == STATUS_RUNNING` if you think that would be cleaner?

**Comment by jeremystretch** [comment]
Sorry, forgot about setting it to `RUNNING` first. What you have should be fine.

**Comment by glennmatthews** [comment]
Weird Travis failure for Python 3.7, looks unrelated to my changes.

**Comment by jeremystretch** [comment]
@glennmatthews yeah ignore those, something wonky is going on.

**Comment by jeremystretch** [comment]
FYI tests are fixed

**Comment by glennmatthews** [comment]
Is this blocked on "com[ing] up with a more elegant approach to intentionally rolling back a transaction"? Or can we move ahead with this as-is?

**Comment by glennmatthews** [comment]
Looks like [`set_rollback`](https://docs.djangoproject.com/en/3.0/topics/db/transactions/#django.db.transaction.set_rollback) may be the approach to consider.

**Comment by jeremystretch** [comment]
> Is this blocked on "com[ing] up with a more elegant approach to intentionally rolling back a transaction"?

No; that was just a general comment/complaint.

> Looks like set_rollback may be the approach to consider.

Yes! I knew there had to be some mechanism for this. Not sure how I missed this. You can either add this to the PR, or leave it as-is and I'll take it as an action item to implement application-wide.

**Pull request merged**
