### PR TITLE
Proposing link to netboxapi-client community sdk in README

### PR DESCRIPTION
**Pull request by bpetit**
### Fixes:

Nothing. Just proposing a link to a python client library and cli tool I wrote.
Thank you very much for netbox, I love this tool.

### CODE REVIEW

**Comment by bpetit** [comment]
Hi !

First, you're absolutely right, it is not related to any issue. Sorry if I missed a part of the process. This is just a proposal, which can be dropped if of no interest.

Second, at the time I wrote this, I  found no explicit reference to pynetbox (maybe I didn't accurately searched). Nowadays, the only thing I like about this is the cli part, which is a simple argparse wrapper. The few people I know who use it, use it for the same reason. Pynetbox is certainly architectured better. I'd use it if I had to integrate netbox api to a development project. If I had to quickly query the API from the cli, I'd use netboxapi-client.

**Comment by jeremystretch** [comment]
I have several concerns with this project:

1. It seems to be little more than a wrapper for forming an endpoint URL: All data is still passed as raw JSON. Maybe I'm missing something.
2. It somehow claims to be compatible with all future versions of NetBox:

> Current developments are tested on netbox v2.2.2 and above.

3. The last commit was on April 15, 2018.

Also:

> Second, at the time I wrote this, I found no explicit reference to pynetbox

There is a link to it in the README five lines above the link you added.

**Comment by bpetit** [comment]
I meant at the time I wrote the library.

I could be more specific in the README, will do.

You're right, it is still a simple wrapper, just a practical one.

Cheers

**Comment by jeremystretch** [comment]
Sorry but I'm going to decline this. I want to ensure we maintain a high bar for the inclusion of community projects in the interest of minimizing functional overlap and confusion among users.

**Pull request closed without merging**
