### PR TITLE
Added Edit IP Address Functionality 

### LINKED ISSUE #1001: request: Edit IP Address assignment on device overview page.
Would it be possible to when editing an IP Address assignment to an interface, that the interface can be changed without having to delete the assignment and re-create it on a different interface?

Also to add the edit icon next to the delete icon to allow for easy IP Address editing rather than having to click through using the IP Address.

### PR DESCRIPTION
**Pull request by snazy2000**
### Fixes: #1001 

Added functionality to edit IP Address from device page instead of having to remove and re-add

### CODE REVIEW

**Comment by jeremystretch** [comment]
The `return_url` stuff in the object views is a bit messy. We don't want to start adding it as a hidden field in individual forms. It should be possible to just pass it as a GET query parameter. Let me see about cleaning it up a bit.

**Comment by jeremystretch** [comment]
I've reworked how `return_url` is handled in general in f70f0f8. I did end up passing it as a POST parameter, but at least now we have a mixin form that we can use.

**Comment by snazy2000** [comment]
Nice work!

**Comment by jeremystretch** [comment]
Don't bother putting any more work into this for now. I'm working on merging the interface assignment into the IPAddressForm so that we can ditch the assignment view altogether. Will let you know when I have something.

**Comment by jeremystretch** [comment]
#878 and #1001 should be taken care of now. Thanks!

**Pull request closed without merging**
