### PR TITLE
WIP: 3288 diversity of endpoints

### LINKED ISSUE #3288: Connecting rear ports through circuit causes error when connecting devices
### Environment
* Python version: Python 3.6.8
* NetBox version: 2.6.0

### Steps to Reproduce
1. Create a circuit
2. Create two devices with multiple front ports mapped to a single rear port (mux
3. Connect the two rear ports to the circuit
4. Connect an interface to a front port of one mux
5. Connect an interface to the corresponding front port of the other mux

At this point all is still well: both devices are connected to each other.

6. Repeat step 4

This will fail as the first interface connection will have used the circuit termination point id in its `_connected_circuittermination_id`. The second interface will try to put the same termination point id in its `_connected_circuittermination_id`, which will fail because that is a `OneToOneField`.

### Expected Behavior
When connecting multiple devices/interfaces through a mux they are expected to share the same circuit. Use cases are CWDM and DWDM. In Django terms: I expected `_connected_circuittermination_id` to be a `ForeignKey`, not a `OneToOneField`.

### Observed Behavior
```
<class 'django.db.utils.IntegrityError'>

duplicate key value violates unique constraint "dcim_interface__connected_circuittermination_id_key"
DETAIL: Key (_connected_circuittermination_id)=(42) already exists.
```

### Notes
This case seems similar to https://github.com/digitalocean/netbox/issues/3193, but is different. That issue applies to cables where the rear port of one mux isn't directly connected to the rear port of another mux, but is passed through other patch panels (implemented as 1 front port mapped to 1 rear port).

### PR DESCRIPTION
**Pull request by steffann**
### Fixes: #3288 

This branch is where I'm developing my solution to #3288. I'm creating this WIP pull request to make it easier to track what I'm doing for those who are interested.

### CODE REVIEW

**Comment by steffann** [comment]
A summary of the changes:
- I have changed `connected_endpoint` on Interface, CircuitTermination, ConsolePort and ConsoleServerPort into a GenericForeignKey
- `connection_status` still reflects the same status, but some extra thought on whether this is what we want would be helpful. For example a circuit connected to a rear MUX port seems connected to me
- The objects mentioned above now also have a `_trace` field that stores a list of endpoints traversed between the current endpoint and the connected endpoint. This is stored in a JSONField in a GenericForeignKey-like format
- I created a `CachedTraceModel` abstract model that implements the saving and loading of that
- And of course the templates are adapted to use and show this information

**Comment by steffann** [comment]
And before I forget to mention it: I also adapted the tests to check the behaviour described above

**Comment by steffann** [comment]
Hmmm. I just created a link between a circuit and a front port and that caused an infinite loop. Investigating…

**Comment by steffann** [comment]
I created a demo test case where Site A and Site B are connected using a DWDM circuit with a mux at both ends. Eth1 of router at Site A is connected over `CH35` to the router at Site B.

I also connected a second mux at Site A to the `Upg` port of the first mux. Eth2 of the router at Site A is connected to `CH50` of the second mux. At site B the `Upg` port of the mux is conneced to another circuit going to Site C. At that site there is a mux of the same type as the second mux at Site A, and the router at Site C is connected to `CH50` of that one.

Just to create a scenario with nested muxes and multiple circuits :)

The interfaces of Router A now look like this:

Schermafbeelding 2019-10-23 om 13 43 57

**Comment by jeremystretch** [comment]
This is way too much change for a single PR purporting to address a bug. Any substantial changes to the data model require discussion and agreement beforehand. For example:

> I have changed `connected_endpoint` on Interface, CircuitTermination, ConsolePort and ConsoleServerPort into a GenericForeignKey

We intentionally avoid using generic foreign keys wherever possible because they impede our ability to filter on related objects.

It's clear you've put in a lot of work here, but more discussion and agreement is needed on the root issue presented in #3288 before any disruptive changes will be accepted. At a minimum, altering the intended behavior of NetBox requires a new feature request and use case. I'm going to close this PR for now; let's re-focus the discussion under #3288 to see what can be done to address that issue specifically.

**Comment by steffann** [comment]
> This is way too much change for a single PR purporting to address a bug.

It was never a bug, it has always been a feature request… I never understood why you labeled it as a bug in the first place.

**Comment by steffann** [comment]
The feature request, discussion and use case have been in #3288 for months!

**Pull request closed without merging**
