### PR TITLE
Fixes 3803 

### LINKED ISSUE #3803: Replace logo image with SVG
### Proposed Changes
Replace the existing `netbox_logo.png` with an SVG.

New:
image

> It looks freakin' **glorious** at a larger size; check out `README.md` in the pull request.

Old:
image

### Justification
* Easier to maintain/change in the future
* Scales to size 
* Simple (I only had to use circles and rectangles)
* Smaller (50% of old)

I've created two variants, [one](https://jsfiddle.net/mpor7k1z/) with the title and [one](https://jsfiddle.net/9v08pou6/) without it.

> I couldn't tell which font is in the old logo so I used what most-closely matched it.
<details>
  <summary>netbox_logo.svg </summary>

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 320">
  <style>
    .title {
      font-weight: bold;
      font-size: 200px;
      font-family: "Avenir", "Helvetica Neue", Helvetica, Arial, sans-serif;
      letter-spacing: 4px;
    }
  </style>
  <g fill="#9cc8f8" stroke="#9cc8f8">
    <circle cx="37" cy="284" r="23"/>
    <circle cx="101" cy="37" r="23"/>
    <circle cx="101" cy="220" r="23"/>
    <circle cx="284" cy="220" r="23"/>
    <rect x="93" y="37" width="16" height="180"/>
    <rect x="101" y="212" width="180" height="16"/>
    <rect x="93" y="212" width="16" height="90" transform="rotate(45 101 220)"/>
  </g>
  <g fill="#1685fc" stroke="#1685fc">
    <circle cx="284" cy="37" r="23"/>
    <circle cx="37" cy="101" r="23"/>
    <circle cx="220" cy="101" r="23"/>
    <circle cx="220" cy="284" r="23"/>
    <rect x="37" y="93" width="180" height="16"/>
    <rect x="212" y="101" width="16" height="180"/>
    <rect x="212" y="93" width="16" height="90" transform="rotate(225 220 101)"/>
    <text x="380" y="150" alignment-baseline="middle" class="title">netbox</text>
  </g>
</svg>
```
</details>

<details>
  <summary>netbox_icon.svg</summary>

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 320">
  <g fill="#9cc8f8" stroke="#9cc8f8">
    <circle cx="37" cy="284" r="23"/>
    <circle cx="101" cy="37" r="23"/>
    <circle cx="101" cy="220" r="23"/>
    <circle cx="284" cy="220" r="23"/>
    <rect x="93" y="37" width="16" height="180"/>
    <rect x="101" y="212" width="180" height="16"/>
    <rect x="93" y="212" width="16" height="90" transform="rotate(45 101 220)"/>
  </g>
  <g fill="#1685fc" stroke="#1685fc">
    <circle cx="284" cy="37" r="23"/>
    <circle cx="37" cy="101" r="23"/>
    <circle cx="220" cy="101" r="23"/>
    <circle cx="220" cy="284" r="23"/>
    <rect x="37" y="93" width="180" height="16"/>
    <rect x="212" y="101" width="16" height="180"/>
    <rect x="212" y="93" width="16" height="90" transform="rotate(225 220 101)"/>
  </g>
</svg>
```
</details>

### PR DESCRIPTION
**Pull request by hSaria**
### Fixes: #3803
Replaced the current PNG logo (raster-based) with an SVG one (vector-based).

> I kept the old logo, but I don't think it is being referenced anymore.

### CODE REVIEW

**Comment by jeremystretch** [comment]
Looks great! One minor issue: in `netbox_logo.svg`, the text appears to be aligned along the top of the image, rather centered vertically with the icon. (Or, the bottom of the text is aligned along the vertical center of the image. I can't really tell.) Do you see this as well?

netbox_logo

**Comment by hSaria** [comment]
That's odd. Which platform (OS and web browser) are you on? I don't think I used anything new or special in the SVG, but perhaps I did.

**Comment by jeremystretch** [comment]
This is using Firefox on Linux Mint. I see the same thing when viewing the SVG code on JSFiddle.

**Comment by jeremystretch** [comment]
[This](https://stackoverflow.com/questions/41822995/inconsistent-svg-text-alignment-in-chrome-and-firefox) looks relevant.

**Comment by hSaria** [comment]
[`alignment-baseline`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline) is set to `middle` but maybe that has limited [supported](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline#Browser_Compatibility).

**Comment by hSaria** [comment]
[This](https://jsfiddle.net/93cyxt4m/) works on FireFox, though I'm gonna test it own on other platforms too given the unknown support for `alignment-baseline` and `dominant-baseline`.

**Comment by hSaria** [comment]
I could just use `path` instead of `text` for "netbox" which will two-birds-one-stone it:

* People that don't have the `Avenir` font won't see the fallback fonts
* Won't have to rely on `alignment-baseline` nor `dominant-baseline` to positing "netbox"

The downside is that changing the "font" won't be as easy as it would've gotten converted to a path.

**Comment by hSaria** [comment]
How about [this](https://jsfiddle.net/aupk4ech/)? Had to play around, but got it working with the help of [text-to-svg](https://github.com/shrhdk/text-to-svg) and some "finesse," if you will.
```javascript
TextToSVG = require('text-to-svg');
textToSVG = TextToSVG.loadSync('Avenir-Heavy-05.ttf');

console.log(textToSVG.getD('netbox', {fontSize: 200, anchor: 'top', letterSpacing: 0.02}));
```

**Comment by jeremystretch** [comment]
Can't say I have a strong opinion either way, so long as it's widely supported. I do like that the path approach ensures consistency regardless of installed fonts.

**Comment by jeremystretch** [comment]
Let's go with the path approach for now. We can always revert to the text approach later on if needed for some reason.

**Pull request merged**
