### PR TITLE
CSV Import & Export Custom Fields

### LINKED ISSUE #568: Bulk import custom fields
I'd like the possibility, one some custom fields are defined, to have them importable in bulk.

### PR DESCRIPTION
**Pull request by anthonyeden**
### Fixes: #568 

This pull request is my first attempt at resolving ticket #568.

With these changes, you can now import Custom Fields to Devices. The UI has been updated, and a new version of CSVChoiceField has been created to map the select-field labels to the DB values when performing an import.

It also adds custom fields to the CSV Exporter, using the same column headings as the importer.

If these changes are correct, we need to enable Custom Field importing for all other models by replacing 'forms.ModelForm' with 'CustomFieldForm' in the inheritance of the remainder of the CSVForm models.

### CODE REVIEW

**Comment by anthonyeden** [comment]
This pull request now encompasses all CSV Import models. I'd appreciate anyone testing it, and reporting back here.

**Comment by tpomerhn** [comment]
Hey all, we just tried this on a dev server and it works well (even updates the Import screen for custom vars and adds them as required when so tagged), we'd like this change to go in so we can more easily import/export test data blobs between dev servers before we go to production and we have 36 custom fields at present. Any chance this could get committed to main? Looks like a fairly straightforward merge of a new class...

**Comment by Mark32** [comment]
Hi. Newbie question .. how do I add this branch to my local netbox installation as a branch? Latest release is installed and working and urgently need this custom field import facility (thanks for providing). Thanks

**Comment by Mark32** [comment]
I've installed from fresh cloning https://github.com/anthonyeden/netbox.git

However the custom field import is not available. What do I need to do to get what is missing in order for this to work? This is a test system. Thanks, Mark

**Comment by tpomerhn** [comment]
I'm new to git as well, I think you need to clone the specific branch. 

Check out https://confluence.atlassian.com/bitbucket/checkout-a-branch-into-a-local-repository-313466957.html

You'll need the branch "dev_csvcustomfields"
hth

**Comment by Mark32** [comment]
Thanks tpomerhn that really helped. 

# git branch -a
* (HEAD detached at origin/dev_csvcustomfields)
  develop
  remotes/origin/HEAD -> origin/develop
  remotes/origin/dev_csvcustomfields
  remotes/origin/dev_saml
  remotes/origin/develop
  remotes/origin/develop-2.6
  remotes/origin/master

# git checkout remotes/origin/dev_csvcustomfields

# git branch
* (HEAD detached at origin/dev_csvcustomfields)
  develop

**Comment by Mark32** [comment]
Thanks anthonyeden for providing this fundamental and key functionality. I will be importing tenants with custom fields and will provide feedback. Thanks!

**Comment by Mark32** [comment]
I'm able to import having defined various custom fields. However it breaks when trying to run an export from anywhere. I get:

<class 'TypeError'>

'dict' object is not callable

Screenshot 2019-07-22 at 11 47 26

**Comment by sgreen1** [comment]
Any update on this? I'm also needing to import a ton of custom fields.

**Comment by crytectobi** [comment]
> I'm able to import having defined various custom fields. However it breaks when trying to run an export from anywhere. I get:
> 
> <class 'TypeError'>
> 
> 'dict' object is not callable
> 
> Screenshot 2019-07-22 at 11 47 26

I can confirm that. Import is working fine, export always resolves in that error.

**Comment by jeremystretch** [comment]
@anthonyeden can you address the reports above concerning broken export functionality?

**Comment by lampwins** [comment]
@anthonyeden Are you able to address these issues? Otherwise, this PR will have to be marked as stale.

**Comment by anthonyeden** [comment]
@lampwins Apologies, I must've missed the last message. Yes, I will set aside some time to address this.

**Comment by jeremystretch** [comment]
I'm going to close this PR as it has been inactive for months and likely needs to be rebased against the current `develop` branch. However the issue it addresses (#568) remains open so please feel free to submit at any time once updates have been made in the source branch.

**Pull request closed without merging**
