### PR TITLE
Add MAC address to interface

### PR DESCRIPTION
**Pull request by peelman**
This is my first foray into a Django app...so feedback and/or modifications are welcome...

### CODE REVIEW

**Comment by mdlayher** [comment]
Did you pull latest develop before making this PR?  It appears that you may have created it off the master branch.  The only commit in the PR should be your change.

**Comment by peelman** [comment]
@mdlayher I think things are fixed now.  Updates to the `tests/` files are coming shortly.

**Comment by jeremystretch** [comment]
I'd rather not introduce yet another dependency (`django-macadress`). It should be fairly simple to create our own `MACAddress` field in `ipam.fields` using PostgreSQL's native [`macaddr` type](https://www.postgresql.org/docs/9.1/static/datatype-net-types.html).

**Comment by peelman** [comment]
I started down that path.  The package was doing a lot more than I ever intended to do in terms of validation or what not.

Its probably better than somebody more familiar with Django reinvent that particular wheel then, if you're set against dependencies (noble, to be sure).  I had it storing values pre-inclusion, but the validation was failing miserably, and I would be starting from a place of complete ignorance when it comes to getting Django to write into a different PG datatype.

**Comment by peelman** [comment]
@jeremystretch Well, I gave it a shot...it looks like it might be right...

**Comment by jeremystretch** [comment]
There shouldn't be any need to save the vendor, since that information is already contained in the OUI (first half of the MAC address) and AFAIK doesn't change. If we do want to display the vendor, I think the optimal approach is to store a local copy of the IEEE's OUI database.

**Pull request merged**
