### PR TITLE
Add support for custom fields in tables

### LINKED ISSUE #5344: Support custom fields in user table configuration
### Environment
* Python version: 3.7.3
* NetBox version: 2.9.9 and [develop-2.10](https://github.com/netbox-community/netbox/commit/f3f3993963bac7104edc51bd777887462e7dd5af)

### Proposed Functionality

Support custom fields to be included in list views by making them user configurable (table configuration).

### Use Case

A custom field might be important enough to see it in various list views. This is important to be able to compare it with other objects of the same model. Also, when doing quality assurance, one might want to sort on custom field and then use the bulk edit to normalize the values.

This has been reported before but got closed:

* #492 which is related but did not cover this feature in its initial request, but later in the discussion. Seems it has been overlooked when it got closed.
* #2028 and #2460 asked exactly the same but got closed by #492.
* #1997 Was not clear if #492 was meant.

Cc: @eloquentheit, @sampl3x, @mryauch, @hanej, @lesinigo, @Grokzen, 

### Database Changes

I assume not now that #4878 is done.

### External Dependencies

None.

### PR DESCRIPTION
**Pull request by TomGrozev**
### Fixes: #5344

This adds support for having custom fields in list view tables. All changes are make in the BaseTable class to prevent changing on every table object. Since the custom fields are JSON, if the value is a list they will be displayed as labels.

The mentioned issue is marked blocked but this should be removed since the release of 2.10.

### CODE REVIEW

**Comment by ypid** [comment]
Works nicely :+1: I applied this patch on v2.10.1 and just tested a bit. I will continue using this patch and see if anything breaks.

**Comment by ecoutinho** [comment]
On v2.10.2 is also working has expected. Thanks for this feature.

**Comment by DanSheps** [comment]
@ypid @ecoutinho Keep in mind we will not support you deploying this to your current instances and you will be responsible for resolving any issues you encounter yourself.

**Comment by tom0010** [comment]
I just tested on the docker instance (v2.10.3) - working fine for me right now, so thanks. 
When can we expect this to be merged? 
How is this different to https://github.com/netbox-community/netbox/issues/5576?

**Comment by ecraven** [comment]
just tried this on 2.10.3 (by just replacing the entire table.py file), and it works fine in IP Addresses view. But when looking at one Prefix, and at its ip addresses, I see the following:
maim
Each reload changes the number of times the fields are repeated, sometimes only once, sometimes many times.
This is a great patch, would be very helpful to get it merged!

**Comment by ixinshang** [comment]
> just tried this on 2.10.3 (by just replacing the entire table.py file), and it works fine in IP Addresses view. But when looking at one Prefix, and at its ip addresses, I see the following:
> maim
> Each reload changes the number of times the fields are repeated, sometimes only once, sometimes many times.
> This is a great patch, would be very helpful to get it merged!

Replaced the entire tables.py
same problems too in "dcim/devices/"

**Comment by xkilian** [comment]
@TomGrozev Can you adress the issues raised by @ecraven and @ixinshang? I think we are not too far off.

**Comment by keitarobr** [comment]
> @TomGrozev Can you adress the issues raised by @ecraven and @ixinshang? I think we are not too far off.

A quick fix:

```diff
(venv) rodrigo@ufsclinux:~/CGR/netbox/netbox$ git diff
diff --git a/netbox/utilities/tables.py b/netbox/utilities/tables.py
index 4a796435..cd5af482 100644
--- a/netbox/utilities/tables.py
+++ b/netbox/utilities/tables.py
@@ -33,7 +33,7 @@ class BaseTable(tables.Table):
             label = cf.label if cf.label != '' else cf.name
             self.base_columns[name] = CustomFieldColumn(verbose_name=label)
             custom_fields[name] = cf
-        self._meta.fields += tuple(custom_fields.keys())
+        self._meta.fields += tuple(x for x in custom_fields.keys() if x not in self._meta.fields)
 
         # Init table
         super().__init__(*args, **kwargs)
```

**Comment by ixinshang** [comment]
> > @TomGrozev Can you adress the issues raised by @ecraven and @ixinshang? I think we are not too far off.
> 
> A quick fix:
> 
> ```diff
> (venv) rodrigo@ufsclinux:~/CGR/netbox/netbox$ git diff
> diff --git a/netbox/utilities/tables.py b/netbox/utilities/tables.py
> index 4a796435..cd5af482 100644
> --- a/netbox/utilities/tables.py
> +++ b/netbox/utilities/tables.py
> @@ -33,7 +33,7 @@ class BaseTable(tables.Table):
>              label = cf.label if cf.label != '' else cf.name
>              self.base_columns[name] = CustomFieldColumn(verbose_name=label)
>              custom_fields[name] = cf
> -        self._meta.fields += tuple(custom_fields.keys())
> +        self._meta.fields += tuple(x for x in custom_fields.keys() if x not in self._meta.fields)
>  
>          # Init table
>          super().__init__(*args, **kwargs)
> ```
@keitarobr hi，i changed code in tables.py in 36 line. 
i have a test in device.  it's ok. 
Finally, I hope this feature appears in the official stable version.

thanks all.

**Comment by jeremystretch** [comment]
Thanks @TomGrozev. Merging this into a local branch to wrap it up for v2.11.

**Pull request merged**
