### PR TITLE
Closes #2655: Add FibreChannel QSFP28 (4x32GFC) interface form factor

### LINKED ISSUE #2655: Add FibreChannel QSFP28 (4x32GFC) interface support
### Environment
Python version: 3.6.7
NetBox version: v2.5-beta1

### Proposed Functionality
Shortly after raising #2597 I was made aware that there is not just a single 32GFC interface but also a quad variant. This interface type is known as 4x32GFC QSFP28 (Brocade part number [XBR-000275](https://docs.broadcom.com/docs/12379902)).

I would really appreciate it if this could be added to Netbox and love to put in the work to do it myself.

### PR DESCRIPTION
**Pull request by swerveshot**
### Fixes: #2655
- Adding support for FibreChannel QSFP28 (4x32GFC) interface form factor

### CODE REVIEW

**Comment by jeremystretch** [comment]
I've added this as 128GFC. I should note that as of v2.5 we no longer need to update migrations for changes to a field's choices. (Choices are now ignored as they don't have any effect on the database schema.)

**Comment by swerveshot** [comment]
Alright @jeremystretch thanks for the feedback and adding the 128GFC interface form factor. Much appreciated!

**Comment by jeremystretch** [comment]
Thank you for the PR though! Sorry, it's been a bit hectic this morning.

**Comment by swerveshot** [comment]
And here I was trying so hard to understand git and how to make updates available in the base fork. 😆
But jokes aside; don't sweat it. You're doing a great job.

**Comment by DanSheps** [comment]
@swerveshot git/github is a valuable skill.  I use git every day as a neteng to store my configs so that they are versioned.

**Pull request closed without merging**
