### PR TITLE
Fixes #2050: Include Image Preview via popover

### LINKED ISSUE #2050: Images preview
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.4
* NetBox version:  2.3.2

### Description
We used to attach a variety of picture (setup, custumers install proof etc ...) to each rack, and it's not too easy to find the good one.
It could be very nice to display a gallery of preview instead of just a table with the name/size/date.

### PR DESCRIPTION
**Pull request by tb-killa**
### Fixes: #2050

This PR provide the "Images preview" via bootstrap included popover-method.

image

### CODE REVIEW

**Comment by jeremystretch** [comment]
I don't think this approach would work well for large images. Many people simply upload unedited high-resolution photos directly to NetBox, which I'd expect to be cropped pretty severely. NetBox also doesn't store thumbnails of images. A full-page light box (as suggested in #2050) or modal might work better.

**Comment by tb-killa** [comment]
The request results by a simple solution for image preview if uploaded. The creator doesn't want to click on every link to find the needing picture. I simple use the bootstrap popover for mouseover preview. If you want to show you click on link like original builded.
I think modal or full page image box sound more overload for the simpel request.

**Comment by jeremystretch** [comment]
The screenshot you provided uses a small image. Try it with a typically 4608x2112 or similarly large photo and I think you'll see what I mean. The Bootstrap popup wasn't intended to hold very large elements.

**Comment by tb-killa** [comment]
Damn ;) 
This could be really a strange result.
Will test them tomorrow :)

**Comment by jeremystretch** [comment]
Closing due to inactivity.

**Pull request closed without merging**
