### PR TITLE
16394 distinguish product edition

### PR DESCRIPTION
**Pull request by andrewgormley**
### Fixes: #16394

1. Added SVG files for light and dark netbox labs logos and geometric motif
2. Altered navigation to show specific logo and motif depending on netbox edition
3. Added subtext below logo to display edition for any edition that is not 'Community'

### CODE REVIEW

**Comment by jeremystretch** [comment]
@andrewgormley looks like there's an issue with the SVG logo on top of the background image on mobile view:

screenshot

**Comment by andrewgormley** [comment]
Changes:
- Removed labs logos
- Added sub text for all editions
- Cleaned up motif implementation
- Removed motif for mobile view (it's difficult to implement this in the limited space without it looking like a bug in an already small crowded area. Assuming the majority of users view netbox on desktop this would be a minimal issue.

Outstanding issues:
- in dark mode when navigating to a new page the side navigation flashes white
- on cloud/enterprise editions the motif is incorrectly positioned when opening a sub menu that causes the container to overflow and scrolling down. This issue is solved by using a background-image instead of a standalone  tag, however the background gradient needs to change based on the theme selected. I have not yet found a way to implement the background image and gradient together while also being able to change the gradient with the theme.

Screenshot 2024-07-17 at 23 22 05

**Comment by andrewgormley** [comment]
the motif bug is now fixed

**Comment by jeremystretch** [comment]
I've pushed a small change that should resolve the navbar flickering. @andrewgormley please let me know if this works for you.

**Review by jeremystretch — APPROVED** [review]

**Comment by andrewgormley** [comment]
@jeremystretch I've just edited the style of the edition text to better match the now lowercase type. I think we're good to go on this one now.

**Pull request merged**
