### PR TITLE
Enable serving NetBox from non-root location

### PR DESCRIPTION
**Pull request by pkorovin**

### CODE REVIEW

**Comment by pkorovin** [comment]
Closes [Issue #212](https://github.com/digitalocean/netbox/issues/212)

**Comment by jeremystretch** [comment]
Rather than prepending a prefix to every instance of an APISelect widget with a hard-coded URL, we should change them so that the URL is determined dynamically (this is tech debt included in the original 1.0 release).

**Comment by pkorovin** [comment]
Jeremy, I agree that it's anything but the elegant solution to the problem. I had a hard time making NetBox running on OpenBSD httpd + uwsgi from non-root location so I did this quick straightforward fix and decided to share in hope that it will save some hours for somebody like me :)
Thank you for you efforts and for the good product! Thanks to DigitalOcean for supporting your work!

**Comment by jeremystretch** [comment]
No worries, thanks for the contribution! I'll see if I can get this knocked out quickly.

**Pull request closed without merging**
