### PR TITLE
Closes #2638: Copy Button for Secrets

### LINKED ISSUE #2638: 'copy' button to copy passwords next to unlock
### Environment
* Python version:  3.5.3
* NetBox version:  2.4.4

Hi,

I would love to see a copy button next to the 'unlock' button for passwords under secrets menu.
Is this something that is easily to implement?
Unfortunately I'm just a simple user and have no knowledge on how to do such thing myself. 

### Proposed Functionality

Add a simple 'copy' button next to the unlock button on the device page.
http://example.com/dcim/devices/1/ under 'Secrets'.

### PR DESCRIPTION
**Pull request by hSaria**
### Fixes: #2638

Added a copy button after unlocking secret. 

As mentioned in #2638, the clipboard cannot be modified while running an asynchronous operation (like AJAX call) since the user-triggered event would have been processed before the response is received.
There are hacky solutions, but I'd rather keep things simple. There is a [draft API](https://www.w3.org/TR/clipboard-apis/) that addresses this challenge, but its support is not [wide enough](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText), yet.

Note: I have purposefully avoided adding the copy button to the secret_edit.html page as I see it as unnecessary (you wouldn't normally go to edit to unlock then copy the secret). However, if you'd like it there for consistency, you can copy the button from secret.html (that's the only change needed).

### CODE REVIEW

**Comment by hSaria** [comment]
copy-secret

**Comment by jeremystretch** [comment]
Looks like the changes from #2849 got caught in this PR too. Can you separate the origin branches so we avoid conflating the two in a single PR please?

**Comment by hSaria** [comment]
Oh sorry. My bad. I'll create a new pull request and reference it here.

**Comment by hSaria** [comment]
#2860 created with a fixed origin.

**Pull request closed without merging**
