### PR TITLE
Fixes #164 (partially) - Add region field to site

### LINKED ISSUE #164: Support for Regions
1. At the very least, allow for support to introduce regions for sites.  It could later be expanded to auto assign sites to regions based on country logic (ie setup rules to auto assign a site to a region).
2. Regions could also be applied to subnets for better IPAM either directly like sites or indirectly via Region -> Site -> Rack/Rack Group -> Device(s) -> Interface(s) -> Subnet.  From Issue #155 this may not be enough as subnets could be assigned to a client but not on a netbox managed device (ie it could be advertised via a routing protocol and not directly connected).

### PR DESCRIPTION
**Pull request by rdujardin**
Hello. I added a charfield "region" in model Site. It allows to distinguish, for instance, sites in different cities. That was asked in issue #164 .

### CODE REVIEW

**Comment by jeremystretch** [comment]
It's a good start, but there's a lot more work needed to implement a new model. We need views for creating, editing, and deleting objects, as well as API serializers and endpoints.

**Comment by rdujardin** [comment]
Sorry I didn't understand, do you mean region should be a new model and not only a field ?

**Comment by jeremystretch** [comment]
Yes, we would need to define a Region model (similar to the Site model) as well as the views, forms, and API mechanisms for it.

**Comment by rdujardin** [comment]
Okay, I'm doing that. Should site-to-region linking be mandatory ?

**Comment by jeremystretch** [comment]
No, any new relationships being added to the NetBox data model must be optional.

**Comment by jeremystretch** [comment]
Closing due to inactivity

**Pull request closed without merging**
