### PR TITLE
Multiselect

### LINKED ISSUE #8704: shift click to select multiple boxes
### NetBox version

v3.1.8

### Feature type

New functionality

### Proposed functionality

I am fairly new to this, but I want a function where you click the first tic box, hold down shift and click the last tic box you need. Then you have selected all the tickboxes in between.

### Use case

When you are selecting multiple devices, a feature where you can select all by holding in shift after ticking one box, and then clicking on the last box that you need would save some time instead of clicking a tick box on every single device.

### Database changes

_No response_

### External dependencies

_No response_

### PR DESCRIPTION
**Pull request by CroogQT**
### Fixes:  #8704 

Allows a user to shift click a checkbox to set the "checked" value of all check boxes between their selection and their previous selection to the new value of their selected checkbox.

### CODE REVIEW

**Comment by LHBL2003** [comment]
So does this new feature support my feature suggestion?

https://github.com/netbox-community/netbox/issues/9307

Or is something else meant here?

**Comment by kkthxbye-code** [comment]
@LHBL2003 - This is not related to your issue no.

**Comment by CroogQT** [comment]
Hopefully this will help clarify the intent of #8704 as I understand it.

https://user-images.githubusercontent.com/16785887/167200153-11433cbb-c8f5-4842-a565-69ca2824d525.mov

**Comment by kkthxbye-code** [comment]
Tried it out, works great!

Found a very minor issue:

* Click one or more checkboxes
* Search for something in the Quick Search input
* Remove the search string from Quick Search again
* Shift click any checkbox

Everything from the bottom of the table and to where you clicked will be marked. The reason is that when using the Quick Search the table is replaced by HTMX. As such the state of the previous element will be wrong (doesn't exist anymore) and it will mark everything as it never finds the target element.

Maybe you can clear the state whenever a HTMX table [has been rendered](https://htmx.org/events/#htmx:afterSettle).

**Comment by CroogQT** [comment]
> Tried it out, works great!
> 
> Found a very minor issue:
> 
>     * Click one or more checkboxes
> 
>     * Search for something in the Quick Search input
> 
>     * Remove the search string from Quick Search again
> 
>     * Shift click any checkbox
> 
> 
> Everything from the bottom of the table and to where you clicked will be marked. The reason is that when using the Quick Search the table is replaced by HTMX. As such the state of the previous element will be wrong (doesn't exist anymore) and it will mark everything as it never finds the target element.
> 
> Maybe you can clear the state whenever a HTMX table [has been rendered](https://htmx.org/events/#htmx:afterSettle).

Ah! Great catch and great solution! Will implement shortly. Thanks for the feedback! :)

**Comment by kkthxbye-code** [comment]
@CroogQT - Expect getting some time to work on this? I think it's a great usability improvement.

If you don't have the time I can give it a shot fixing the last small bug.

**Comment by jeremystretch** [comment]
Honestly I'm ok with merging this as-is, even with the bug. Happy to open a separate bug report to track the remaining work.

**Comment by kkthxbye-code** [comment]
More than fine by me.

**Pull request merged**
