### PR TITLE
Closes #14638: Drop support for Python 3.8 and 3.9

### LINKED ISSUE #14638: Drop support for Python 3.8 and 3.9
### Proposed Changes

Increase the minimum supported Python version from 3.8 to 3.10. Remove tests for Python <3.10.

### Justification

We'll be adopting Django 5.0 in NetBox v4.0 (see #14637), which [requires Python 3.10 or later](https://docs.djangoproject.com/en/5.0/releases/5.0/#python-compatibility).

Additionally, Python versions earlier than 3.11 are no longer receiving bug fixes per the [Python release cycle](https://devguide.python.org/versions/).

### Impact

NetBox deployments running Python 3.9 or earlier will need to upgrade their Python version to 3.10 or later.

### PR DESCRIPTION
**Pull request by jeremystretch**
### Fixes: #14638

- Remove CI runners for Python 3.8 and 3.9
- Update documented minimum required Python version to 3.10

### CODE REVIEW

**Review by arthanson — APPROVED** [review]
Should we add Python 3.12 to this as well to the python-version line?

**Comment by jeremystretch** [comment]
I actually just opened #14672 to track Python 3.12 as a separate initiative. (Wasn't sure if it's going to require any other changes so I wanted to handle it separately.)

**Comment by markkuleinio** [comment]
Note that https://github.com/netbox-community/netbox/blob/feature/upgrade.sh still references Python 3.8

**Comment by jeremystretch** [comment]
@markkuleinio good catch, thanks!

**Pull request merged**
