### PR TITLE
Add Graphviz to Topology Maps

### PR DESCRIPTION
**Pull request by bemanuel**

### CODE REVIEW

**Comment by zachmoody** [comment]
I might be missing something, are the topology maps broken in the docker release? What's the thought behind adding the OS packages in addition to the graphiz library we're installing in `requirements.txt`?

**Comment by bemanuel** [comment]
The package isn't included so the system can't generate the map.
After include the map works

**Comment by zachmoody** [comment]
Ok, see what you mean now. I get an error saying it couldn't find the executable w/o the `graphiz` system package. I don't think the `python-pygraphviz` is needed though. Can you resubmit the PR w/o it?

**Comment by bemanuel** [comment]
Yes, I do

**Comment by V5ctor** [comment]
So what the steps to have an operational topology ?

**Comment by V5ctor** [comment]
My bad, I've just seen "Files changed" tab.

**Pull request closed without merging**
