### PR TITLE
Banner support

### PR DESCRIPTION
**Pull request by Gelob**
Addresses #73

This adds support for a top and bottom banner/MOTD. Even if we don't merge, the pull can serve as documentation for how to set this up if its something you need.

The banner is configurable by editing the BANNER_TOP and BANNER_BOTTOM variables in configuration.py

Example text:
screen shot 2016-07-06 at 11 46 33 pm

### CODE REVIEW

**Comment by jeremystretch** [comment]
I'm going to be doing some work on the base template soon regarding some miscellaneous rendering bugs. I'll see if I can work in a `div` at the top and bottom for these banners that might save a bit more screen space. (Same for the maintenance banner too.)

**Comment by chagara** [comment]
This is awesome! This is exactly what we need can't wait for it!

**Comment by MaXwellFalstein** [comment]
This is very nice! Exactly what quite a few users wanted! Good work! I am excited to see what the devs put in place with the redesign work.

**Comment by jeremystretch** [comment]
Should we allow the user to define only the banner contents, as in @Gelob's example, or allow them to define the markup for the banner itself as well? Just thinking people might want to change the banner class, for example (info, warning, danger, etc.).

**Comment by chagara** [comment]
Can it be both?

**Comment by Gelob** [comment]
Default bootstrap alert classes would only change the color and I personally don't think thats necessary. Maintenance is already a yellow box so I didn't want them to conflict. I could see if allowed more customization where it might be useful but theirs so many things this could be and we probably should figure that out. I imagine most people might also want a warning on a Login page or maybe they want the   top warning to be closed out and just leave the bottom one remaining, kind of like an acknowledgement.

**Pull request merged**
