### PR TITLE
Update Database Privilege command for PostgreSQL

### PR DESCRIPTION
**Pull request by navjotjsingh**
The updated command will make Netbox work with PostgreSQL 15.

Fixes: #11314

### CODE REVIEW

**Comment by abhi1693** [comment]
This is already documented at https://docs.netbox.dev/en/stable/installation/1-postgresql/ under the section `Database Creation`

image

**Comment by navjotjsingh** [comment]
That doesn't work with Postgresql 15.

**Comment by DanSheps** [comment]
There is a schema permissions change as of PG15:

https://www.crunchydata.com/blog/be-ready-public-schema-changes-in-postgres-15

There are two options as I see it:

1. Alter the database owner
2. Alter the permissions on the schema

I think either are equally as valid but there needs to be more discussion on this first and it should be done through a proper bug report, not a discussion opened that none of the maintainer team has had a chance to comment on or in the PR itself.

Please raise this as a proper BR.

**Comment by navjotjsingh** [comment]
I opened it as a bug report which got converted to discussion.

**Comment by jeremystretch** [comment]
Please resubmit this as a proposed [documentation change](https://github.com/netbox-community/netbox/issues/new?assignees=&labels=type%3A+documentation&template=documentation_change.yaml) and we can discuss.

**Pull request closed without merging**
