### PR TITLE
Basic Support for Python 3

### PR DESCRIPTION
**Pull request by BeryJu**
Imports & everything else adjusted to python3, works with both python 2 and 3. Unit tests succeed for 2.7, 3.4, 3.5 and 3.6: https://travis-ci.org/BeryJu-org/netbox

### CODE REVIEW

**Comment by jeremystretch** [comment]
This is great, thanks!

Django will bump up to 2.0 after 1.11, at which point support for Python 2 will cease.  I'd like to continue supporting Python 2 until then to give users some time to transition. The documentation will need to be adjusted to reflect that both Python versions are supported.

Also, for `settings.py`, let's just use `from netbox import configuration` instead of repeating `netbox.configuration` so many times.

I'm still debating what to do about `ldap_config.py`: It would be nice to absorb it into `configuration.py` but there's an argument to be had for keeping it separate as well. At any rate, let's separate that change from this PR as it's not relevant to Python 3.

**Comment by BeryJu** [comment]
I also have to test this more on python 2 as I think using __str__ brakes the interface because python 2 wants __unicode__.

**Comment by jeremystretch** [comment]
I think we need the `python_2_unicode_compatible()` decorator: https://docs.djangoproject.com/en/1.10/topics/python3/#str-and-unicode-methods

**Comment by BeryJu** [comment]
I was looking for something like `python_2_unicode_compatible` but didn't find anything. I have added to every model that defines a `__str__` in a612012.

**Comment by jeremystretch** [comment]
Looks good to me. FYI this is commit number 1000!

**Pull request merged**
