### PR TITLE
Support VLAN in Import Prefixes, Add VLAN column to Prefixes page

### PR DESCRIPTION
**Pull request by Gelob**
Addresses #42 

This commit adds support for including the VLAN Name when importing prefixes. This also adds the VLAN Display Name to the prefixes view. I've changed the size on the site and role choice fields in in order to save some space because most people will have more VLANs than sites or roles.

The import will throw an error if you have a VLAN with the same VID and name. Its not super descriptive but if anyone has suggestions on how to pull the VLAN Name out of the exception information please let me know.

Screenshot of above described error and other changes to the page's examples
screen shot 2016-07-06 at 2 12 46 am

Screenshot of new view on Prefixes page
screen shot 2016-07-06 at 2 13 35 am

### CODE REVIEW

**Comment by jeremystretch** [comment]
Any reason you opted to use the VLAN name rather than the VID? Doesn't really make a difference but I'd figure the VID might be more convenient.

**Comment by Gelob** [comment]
No real reason, It was based off of the fact that in the prefixes view I would show the vlan display_name and I wanted both to be the same. I figured it was also more likely that you would have multiple VIDs in the same site with different names than you would have multiple VIDs with the same name.

**Comment by jeremystretch** [comment]
Wondering if we should hold off on this until #111 is implemented.

**Comment by Gelob** [comment]
I think its worthwhile to wait and then modify as needed. One thing I constantly found out when researching how to catch the MultipleObjectsReturned exception is that we should try avoid having any duplicate data in backend if possible. If we don't its going to become more of an issue

**Comment by jeremystretch** [comment]
FYI #111 has been tagged for v1.3.

**Comment by jeremystretch** [comment]
Ended up implementing VLAN assignment for prefix import as part of v1.3.0.

**Pull request closed without merging**
