### PR TITLE
fixes for #10070 make l2vpn slug unique

### LINKED ISSUE #10070: Slug for L2VPN has no unique constraint
### NetBox version

v3.3.0

### Python version

3.9

### Steps to Reproduce

1. Create a L2VPN with name `Test` and slug `test`
2. Create a L2VPN with name `Test2` and slug `test`

### Expected Behavior

I expect a warning to be displayed when trying to create the second L2VPN with the same slug as the one before. The slug should be an unique attribute. It is unique for other models i.e. Tenants.

### Observed Behavior

The second L2VPN is created without a warning or an error. Two L2VPN with the same slug exist at the same time.

### PR DESCRIPTION
**Pull request by arthanson**
### Fixes: #10070

Adds unique constraint to L2VPN slug field along with max_length.  Note: Would cause issues migrating if someone already has non-unique slugs defined (probably fairly unlikely).

### CODE REVIEW

**Comment by jeremystretch** [comment]
Looks like a few of the tests are failing simply because they're creating L2VPNs without slug values:

https://github.com/netbox-community/netbox/blob/deee36651d1a2cf464a2ed2ec932f066d8cbeab7/netbox/ipam/tests/test_api.py#L975-L980

**Comment by jeremystretch** [comment]
@arthanson I've just pushed a tweak to `develop` to add slugs for the affected tests. If you rebase this branch it should pass CI now.

**Comment by DanSheps** [comment]
Would it make sense to make slugs unique but non-required?

**Comment by jeremystretch** [comment]
Every model which includes a `slug` field currently requires that field to be populated. Barring any changes per #8113, let's keep consistent with that.

**Pull request merged**
