### PR TITLE
Dashboard tweaks

### LINKED ISSUE #12219: New dashboard widgets have insufficient header contrast in dark mode
### NetBox version

v3.5.0-dev

### Python version

3.8

### Steps to Reproduce

1. Navigate to the dashboard screen with the new widgets.

### Expected Behavior

The text and icon colors within the card header should maintain at least the same contrast ratio between light and dark modes. You can see this done within the search and log in buttons in the screenshots below.

### Observed Behavior

Currently, the colors used for the text and icons for card headers in dark mode do not provide much contrast against the background, making them very difficult to see. Screenshots below for reference.

beta-demo netbox dev_light
beta-demo netbox dev_dark

### PR DESCRIPTION
**Pull request by jsenecal**
### Fixes https://github.com/netbox-community/netbox/issues/12219

* fixes CSS so that the dashboard look and feel more consistent within netbox
* fixes header contrast when no color is selected (https://github.com/netbox-community/netbox/issues/12219)
* fixes scrollbars in cards where applicable
* makes the cards look like they were in 3.4 (beefier header)
* allows for an icon to be added to the card title
* hides the modification buttons when the dashboard is locked

### CODE REVIEW

**Comment by jsenecal** [comment]
Screenshots:
image
image

**Comment by jeremystretch** [comment]
@jsenecal the scope of #12219 is limited to fixing the widget header colors, and arguably related cosmetic issues. While I appreciate all the work in this PR, I'm afraid there are too many changes that have yet to be discussed for a single PR. Could you please separate out the changes which are directly relevant to #12219, and submit new issues for the others?

**Comment by jsenecal** [comment]
Apologies for the delayed response and lack of activity on this pull request. I needed to take some time with my family. I'll be providing a concise summary of the changes in a few FRs/Issues very soon. Thank you for your understanding and patience.

**Comment by jsenecal** [comment]
Hi @jeremystretch , I've opened #13073, #13075, #13076, #13077, #13078, #13079 to track the changes introduced by this PR. Feel free to review them individually.

Should all of them be accepted, I will update this PR to resolve any conflicts. Or otherwise work on re-implementing all these changes in separate PRs should one of the proposed changes be refused.

**Comment by jeremystretch** [comment]
@jsenecal thanks for opening those FRs, but this PR needs to be broken up into multiple PRs that address each FR individually. I'm going to close this PR but you should be able to pull individual commits from the branch into new ones.

**Pull request closed without merging**
