### PR TITLE
Attempts to fix #1527

### LINKED ISSUE #1527: PyCrypto is dead; Use cryptodome
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.6.2
* NetBox version:  Example: 2.1.3

### Description

To replicate, attempt to run this on a windows server / windows box. `pcrypto` won't install and is dead now. replacing it with `pycryptodome` gets you further in the process, but fails when referencing `XOR`

### PR DESCRIPTION
**Pull request by jdell64**

### CODE REVIEW

**Comment by jdell64** [comment]
Travis had issues with this... I apologize, but I don't think I know enough about what the `XOR` function is doing.

**Comment by jeremystretch** [comment]
The XOR function is needed; please review the code further. Removing it breaks everything.

**Comment by jdell64** [comment]
I figured as much, what is this function doing? Is it used for password hashing?

I ask because what I read says to use something else.

**Comment by jdell64** [comment]
Not to further beat a dead horse, but from Crypto:

https://www.dlitz.net/software/pycrypto/api/current/Crypto.Cipher.XOR-module.html

>XOR is one the simplest stream ciphers. Encryption and decryption are performed by XOR-ing data with a keystream made by contatenating the key.
>Do not use it for real applications!

I'm willing to do the work, but I would need some help on how to get started.

**Pull request closed without merging**
