### PR TITLE
Closes #11942: Peer-review workflow

### LINKED ISSUE #11942: Support for a peer-review workflow
### NetBox version

v3.4.5

### Feature type

Data model extension

### Proposed functionality

Extend the [staging mechanism](https://github.com/netbox-community/netbox/pull/10890) to support a peer-review workflow.

The idea here is to provide users with a way of proposing changes, both programmatically and through the UI, and have another team member with more elevated permissions review, approve and apply them.

To support this, we'd need changes across different components and I'd suggest to implement them parts. Phases 1 through 6 are all backend work that can be done incrementally in different MRs. Phases 7 through 9 are all UI work that I believe can be released independently.

##### Phase 1 - Scaffolding for notifications

* Add a new model to represent notifications.
* Extend API (REST and GraphQL) to read, update and delete notifications. Note that notifications are created by the system.

##### Phase 2 - Introduce the `ReviewRequest` model.

* Introduce a new model that represents a `ReviewRequest`. At a minimum this should be associated to a `Branch`
* Extend the API (REST and GraphQL) to CRUD `ReviewRequest`

##### Phase 3 - Enhance `Branch` to identify stale changes.

* Enhance the `apply` function of the `Branch` model to support applying a change on a stale model. To keep things simple, reject stale changes.

##### Phase 4 - Extend the permissions model to support the creation of review requests by non power users.

* Add a new permission type to give users the capability to create review requests.

##### Phase 5 - Extend the `ObjectChange` model to support review/reviewer information.

* Update the model to include review/reviewer information if applicable.

##### Phase 6 - E2E test suite to go through the peer-review workflow programmatically

* At this stage of the implementation, we should have all the backend components to test the workflow end-to-end. Implement a test suite that describes the canonical way of using these new APIs and demonstrates the workflow.

##### Phase 7 - Update the UI to support notifications.

* Add bell style notifications in the top bar.
* Add view to show all notifications, and support actions such as mark as read, unread and delete.

###### Phase 8 - Update the UI to support review requests.

* Add new button type (something analog to the edit button) to support creating a review request.
* Add view to read, diff, update and delete review requests.

##### Phase 9 - Update the change log in the UI.

* Update the UI include reviewer/review information (if applicable).

### Use case

Netbox users with create/edit/delete permissions can independently change the state of an instance.

While convenient from a velocity point of view, the current model doesn't support organizations with strict change management processes that require all production changes to be peer-reviewed. This feature request aim to add that functionality to Netbox.

##### New `Notifications` model (minimum fields required):

* pk
* user (fk to user)
* title
* content
* read flag

##### New `ReviewRequest` model (minimum fields required):

* pk
* owner (fk to user)
* reviewer (fk to user)
* branch
* state (in review, approved, denied)
* status (open, closed)

##### Update `ObjectChange` model (add optional field):

* Review Request (fk to ReviewRequest)

### External dependencies

None that I can think of.

### PR DESCRIPTION
**Pull request by rmanyari**
### Closes: #11942 

* Notification model in `staging` zone.
* ReviewRequest model in `staging` zone.
* Basic REST API implementation under `extras`. Still WIP.
* Support to suggest edits through the UI on `Device` models.
* Generic suggest view and `suggest_form_factory` implementation.
* Generic changes to `ObjectEditView` to support `suggest` action.
* Update `Branch` `__str__` function to convey information about the staged changes.
* Add properties to `Branch` to make it easier to display the differences.
* `ReviewRequest` and `StagedChange` tables implementation.
* `ReviewRequest` views to list, view, approve and deny requests.

### CODE REVIEW

**Comment by rmanyari** [comment]
Got it to a point where there's enough functionality to convey the idea of a `ReviewRequest`.

Here's the idea. An admin can create a permission/role that allows users to suggest changes on different entities. Note that to be able to suggest changes you also need to be able to read information, so we also grant effectively "read all". Here's an example:

image

At this point our dummy user can create `ReviewRequests`. See screenshots below to follow the process:

(We implemented a new "Suggest Edit" action)
image

(dummy user can suggest changes the same way he would edit an object, the only additional, mandatory field, is a reviewer. At the moment, reviewers are super users, I intend to update this to anyone who can modify the object).
image

(On the ReviewRequest is created, the user and the reviewer can both see it in the "Others" tab)
image

(This view presents a list of your requests and the requests you've been assigned. For the sake of demo, I'm switching to my power user view to show the next steps. Note the recently created review by `dummy` assigned to `rodrigo`)
image

(Clicking on this item takes us to a page where we can see the diff, and approve or deny the request. Also note the status and state)
image

(Say we reviewed and want to approve the request, we can click on the `Approve Change` button which will apply the suggested changes and update the state - As of this writing I just noticed an implementation bug, the suggested changes are emptied on approval since they are dynamically calculated. Will fix on the next iteration.).
image

(Finally we can go on the instance to view the latest changes)
image

That's it. Feel free to checkout this branch and play with this a bit.

**Comment by rmanyari** [comment]
Pending functionality:

* Detect stale `ReviewRequest` and implement a way of dealing with them
* Full REST/GraphQL API implementation
* Update function that determines the list of potential approvers to include users who can modify an object and not just admins.
* `Branch` and `StagedChanges` cleanup on removal of `ReviewRequest`.
* Implement check to prevent self reviews
* Support for suggest on all models, not just `Device`.
* Notifications bar and notifications views in the UI.
* Add the ability to re-assign a `ReviewRequest`.

**Comment by jsenecal** [comment]
Many thanks @rmanyari, I'll bring this up to our next maintainers meeting agenda.

**Comment by rmanyari** [comment]
Fantastic - Any early feedback? I'm happy to continue working on the pending stuff I have in my mind, my only concern is that the MR is already getting kinda big and I fear that if we want to get this in, it will difficult to review. Thoughts?

**Comment by jeremystretch** [comment]
@rmanyari nice work getting started with this, however a PR is premature. FR #11942 still needs to be discussed, and if accepted, assigned to a release milestone. You're more than welcome to continue working on this in the meantime, however I have to close this PR per our [contributing policy](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md). Please continue to discuss your work under the feature request.

**Pull request closed without merging**
