### PR TITLE
Service Port functionality #539

### PR DESCRIPTION
**Pull request by if-fi**
Hello netbox maintainers,

This is the functionality for Device Service Ports as described in #539.
It adds possibility to add a Service Port to a Device's IP address.
The port fields include - a reference to an IP address, a type (tcp/udp), a port number, a name and a description.

You will also find functionality to edit and delete and serialize ServicePort.

I am looking forward for your comments.

### CODE REVIEW

**Comment by flokli** [comment]
Hey @if-fi,

it seems like e1d9384f4ef13188e4b1cdcb5a3cd331d995c9b5 should'nt go into this pull request. You might want to add these to your global `.gitignore`, or file it in a separate PR.

Additionally I'd suggest to call the UDP/TCP field of `ServicePort` `protocol` instead of `type`.

Would you mind rebasing your branch to the latest changes, and merge the pep8 fixes into the previous commits while doing so?

**Comment by if-fi** [comment]
Hi @flokli,
I've rebased my branch on top of latest `develop` and I have made the changes you requested.
Please check them out.

**Comment by flokli** [comment]
Hi @if-fi, thanks!

I saw you're using `0.0.0.0/24`, which probably should be `0.0.0.0/32` (RFC3330).

Also, IPv6 is missing totally so far. The unspecified address is `::/128` (RFC5156), and the `clean()` method should respect this (if there is a `ServicePort` on `0.0.0.0/32`, it should still be possible to add one at `2001:db8::1`, but listening on `::/128` normally also includes IPv4, so you can't add any more `ServicePort`s if `::/128` exists.

I'd even strip the netmask completely from the notation, as the underlying `IPAddress` field ony stores addresses without networks anyway.

I'm unsure whether it should still be allowed to specify a device when using unspecified addresses, and how the `clean()` function should handle these cases. @jeremystretch, any opinion on that?

**Comment by flokli** [comment]
@if-fi Can you rebase this again to latest master? Currently it doesn't apply.

**Comment by if-fi** [comment]
@flokli I'll be offline until the end of next week. After that I will rebase again on top of latest changes. I'll also change the mask to `0.0.0.0/32, I can add the IPv6 restrictions as well.
I will also address further comments if you have some, during the upcoming week.

**Comment by if-fi** [comment]
@flokli I have rebased my changes onto the latest `develop` branch and I have also added the support for the IPv6 checks.

I do not think I can omit the netmask because the it is mandatory when new `IPAddress` is created and the column`address` in table `ipam_addresses` contains the netmask concatenated to the address.

**Comment by flokli** [comment]
@if-fi At least `netaddr.IPNetwork('0.0.0.0/32') == netaddr.IPNetwork('0.0.0.0')` returns `True`.
Can you check if it still works when omitting the netmask?
If the netmask needs to stay, then `0.0.0.0/24` should however still be changed to `0.0.0.0/32`.

**Comment by if-fi** [comment]
@flokli I changed the netmask to `0.0.0.0/32`

Since I am doing a db filter like
``` python
bool(ServicePort.objects.filter(
            ip_address__address='0.0.0.0/32', port=self.port, protocol=self.protocol).exclude(pk=self.id))
```
in order to find records in the db for `ServicePort`s assigned to all IP addresses.
If I omit the net mask
``` python
bool(ServicePort.objects.filter(
            ip_address__address='0.0.0.0', port=self.port, protocol=self.protocol).exclude(pk=self.id))
```
what happens is that we get `True` if the port is assigned to `0.0.0.0` address with any other netmask, not only `/32`.

So I suggest we keep the `/32` netmask.

**Comment by flokli** [comment]
`0.0.0.0/24` would'nt make much sense anyways, right? ;-)

When `bind()`ing to an address, there is no way to specify a netmask. The netmask only says which other hosts are directly reachable. I think we should strip the netmask completely, and only store plain addresses (or networks with /32 for IPv6, or /128 for IPv6, if the model doesn't support that)

**Comment by if-fi** [comment]
The ServicePort is connected to the IPAddress table by foreign key. And the IPAddresses in the project are always saved with netmask.

selection_026

and in the db itself the addresses are saved concatenated with the netmask.

I may be misunderstanding what you propose. If you think we can go without a netmask can you please add some pseudocode to your suggestion.

**Comment by flokli** [comment]
Ah, right, I missed the check in [ipam.formfields](https://github.com/digitalocean/netbox/blob/develop/netbox/ipam/formfields.py#L25), which disallows adding addresses without netmask.

Maybe we should add checks there, to only allow `0.0.0.0` with netmask `32` and `::` with netmask `128`, (as other netmasks don't make any sense for these kinds of addresses).

I would however wait for some feedback from @jeremystretch about this, though. These addresses have some corner cases, they need to be hidden from the duplicate ip address check, primary ip fields, global ip addresses listing etc.), which might get messy.

Maybe they should disallowed in `IPAddress` completely, and the reference from `ServicePort` to an `IPAddress` should be optional,  and in case of `Null` interpreted as 'listen on all addresses/interfaces'. We then should still store the address version somewhere in ServicePort, to distinguish `0.0.0.0/32` from `::/128`.

IMHO Netmasks can be stripped from the output in `netbox/templates/dcim/inc/_port.html`, to show the interface name of this address instead (in braces or as a separate column).

**Comment by if-fi** [comment]
@flokli this netmask rework sound like something useful that should be discussed internally in your team. It may have impact on other many parts of _netbox_ and it is for sure out of the scope of ServicePorts feature. 
I suggest that we keep the changes in the spirit of the current version of the system - with netmasks eveywhere. It can easily be reworked if you get rid of the 0.0.0.0 netmasks later, once you reach final decision in your team, how those special IPAddresses should look and behave.

**Comment by flokli** [comment]
@if-fi I'm just a contributor, no project owner ;-)

But I agree, handling `0.0.0.0` and `::` specially can also be handled in a second step, and shouldn't hinder this PR to get merged. The code looks good to me so far, so lets hear what others think about it!

**Review by flokli — APPROVED** [review]

**Comment by jeremystretch** [comment]
Sorry it's taken me so long to comment on this. Here are some thoughts:

* The IPAddress model will always require a mask, because the mask is part of the address. This trait is not specific to NetBox; it's how IP works.

* There should never be a need to create a `0.0.0.0/32` or `::/128` IPAddress object. Instead, any reference to such an object should simply be NULL. (If it's necessary to indicate the address family, that information can be stored elsewhere.)

* It seems like a more efficient approach, rather than associating a service with a particular IP address, would be to assign a service to a device, and allow the user to optionally further specify a particular IP address(es) belonging to that device. If no individual addresses are selected, it can be assumed that the service is reachable via all addresses assigned to that device.

* Instead of using 0 and 1 to indicate TCP or UDP, let's use the [actual IP protocol numbers](https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers) (6 and 17).

This is great work, @if-fi! I'd like to poke at it some more before merging but we can probably get it into v1.8.

**Comment by if-fi** [comment]
@jeremystretch thanks for appreciating the functionality. 

I have reworked the ServicePort feature to be bound to Device and made the IPAddress optional. You can reread it again and see in you have more suggestions for improvements.

I also changed the TCP/UDP options to 6/17.

**Pull request merged**
