### PR TITLE
Fixes #11623: obfuscate Wi-Fi PSKs

### LINKED ISSUE #11623: Hide WIFI password
### NetBox version

v3.4.3

### Feature type

Change to existing functionality

### Proposed functionality

Is it possible to hide the WIFI password as well? As now when you add the password it is added as plain-text.
Can this be a hidden password with "*********" and icon on the side to make it visible?

Or does it needs to be moved to "secret(store) plugin?

### Use case

Well i think passwords dont need to be visible until you want it to be. 
The best part is that you ofcourse need to be logged in to see this. 
But some think this needs to be secure and im not sure if this is also plain text in the database itself? 

### Database changes

Probally yes encrypted and hidden

### External dependencies

Maybe the secret plugin.

### PR DESCRIPTION
**Pull request by decoupca**
### Fixes: #11623

* Changes PSK fields to `PasswordInput`s in edit views
* Obfuscates PSK on object view with show/hide toggle

### CODE REVIEW

**Comment by decoupca** [comment]
@jeremystretch I'm not clear on what I need to push to pass CI checks, please advise

**Comment by abhi1693** [comment]
Try running the following and commit. You are basically missing generated static files

```
cd netbox/project-static
yarn
yarn bundle
```

**Comment by decoupca** [comment]
> Try running the following and commit. You are basically missing generated static files
> 
> ```
> cd netbox/project-static
> yarn
> yarn bundle
> ```

When I do that and run `git status`:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   dist/config.js.map
        modified:   dist/graphiql.js.map
        modified:   dist/lldp.js.map
        modified:   dist/netbox.js
        modified:   dist/netbox.js.map
        modified:   dist/status.js.map
        modified:   package.json
        modified:   src/racks.ts
        modified:   src/search.ts
        modified:   src/util.ts
        modified:   styles/overrides.scss
        modified:   styles/rack-elevation.scss
        modified:   yarn.lock

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .yarn/
        .yarnrc.yml
```

If I do `git add .` then `git commit` it adds a bunch of stuff, tens of megabytes of what looks like yarn build environment stuff. Do I include all that?

**Comment by kkthxbye-code** [comment]
@decoupca - these are the ones you are supposed to push:

        modified:   dist/netbox.js
        modified:   dist/netbox.js.map

However as you've modified package.json it will probably still fail. The .yarn folder and .yarnrc.yml files are probably because you have installed global yarn packages, also not something you should push.

You can revert all that, delete node_modules or whatever it's called and just simply do a yarn and yarn bundle and push the two files I specified.

**Comment by decoupca** [comment]
@kkthxbye-code I started from a clean working tree, reran yarn and yarn bundle, ended up with the same git status as before. But pushed only your 2 files, all good. Not sure where all the other changes came from.

**Comment by jeremystretch** [comment]
Thanks @decoupca!

**Pull request merged**
