### PR TITLE
Closes #6582: Allow available-ips to specify network bits

### LINKED ISSUE #6582: Allow available-ips to specify network bits
### NetBox version

v2.10.6

### Feature type

Change to existing functionality

### Proposed functionality

Allow the `POST /ipam/prefixes/{id}/available-ips` to specify prefix length (for example when I need to create /32's)

### Use case

Specifying custom network bits.

### Database changes

_No response_

### External dependencies

_No response_

### PR DESCRIPTION
**Pull request by cpaillet**
### Fixes: #6582

Allow the POST /ipam/prefixes/{id}/available-ips to specify prefix length (for example when I need to create /32's)

### CODE REVIEW

**Comment by ThomasJLLN** [comment]
Hello @jeremystretch, 
Could you please take a look at this PR?
Thanks

**Comment by cpaillet** [comment]
Hi,
Is it possible to have the workflow approval ?
thanks

**Comment by jeremystretch** [comment]
Please follow the template when submitting a pull requests to ensure that it is linked to the corresponding issue automatically.

**Comment by cpaillet** [comment]
Sorry, I didn't find any template in the documentation. I try to change Closes by Fixes in the PR  comment ?

**Pull request closed without merging**
