### PR TITLE
Closes #8595: Added new PON interface types

### LINKED ISSUE #8595: Add PON ports to interface type
### NetBox version

v3.1.7

### Feature type

Data model extension

### Proposed functionality

Add EPON, GPON, X-GPON and other type of PON ports to interface type.

### Use case

These ports are used for OLTs in FTTH scenarios.

### Database changes

_No response_

### External dependencies

_No response_

### PR DESCRIPTION
**Pull request by DorianBourgeoisat**
### Closes: #8595:
Added the interface types as listed in #8595 for PON technologies.

### CODE REVIEW

**Comment by jsenecal** [comment]
What about  NG-PON2?

**Comment by DorianXGH** [comment]
What do you mean ?
It is included, with 
`(TYPE_TWDM_PON, 'TWDM-PON (NG-PON2) (4x10 Gbps)'),`
NG-PON2 and TWDM-PON are the same thing, according to wikipedia https://en.wikipedia.org/wiki/NG-PON2
Maybe we should invert NG-PON2 and TWDM-PON as it true that NG-PON2 is more used than TWDM-PON, but it depends on the manufacturer, Nokia/Alcatel uses TWDM-PON for example.

**Comment by jsenecal** [comment]
> What do you mean ? It is included, with `(TYPE_TWDM_PON, 'TWDM-PON (NG-PON2) (4x10 Gbps)'),` NG-PON2 and TWDM-PON are the same thing, according to wikipedia https://en.wikipedia.org/wiki/NG-PON2 Maybe we should invert NG-PON2 and TWDM-PON in the name as it true that NG-PON2 is the most prevalent one, but it depends on the manufacturer, Nokia/Alcatel uses TWDM-PON for example.

I actually had deleted my comment before you replied ahaha, I didn't see NG-PON2 at first ben then saw it and removed my comment.

These look good to me, paired with the new cabling functionality in v3.3 they will be awesome.

**Comment by vista-** [comment]
NG-PON2 is definitely the more well-known name of the technology, I glanced over it the first time as well.

Just 2-cents

**Comment by vista-** [comment]
There's also XG-PON (10G down, 2.5G up) out there, but I'm not sure how widespread is the adoption of that standard, as it's been largely succeeded by XGS-PON.

**Comment by jeremystretch** [comment]
Keep in mind that none of this is set in stone; we can add additional types in the future if the need arises. What I'm more concerned with is ensuring that whatever we _do_ add is accurate, to avoid having to alter the existing choices.

**Comment by DorianXGH** [comment]
I've changed it from TWDM PON to NG PON2 as the main name, with TWDM in parentheses.
It is the only one with a 2nd name used in real life as far as I know.
But yeah, I've seen the deleted reply asking about the asymmetrical XG-PON, it's also in there :)

**Comment by jeremystretch** [comment]
CI failures are unrelated to the change being made and have already been resolved in `develop`.

**Comment by jeremystretch** [comment]
Thanks @DorianXGH and @jsenecal!

**Pull request merged**
