### PR TITLE
Capitalize Filter Form Labels

### LINKED ISSUE #16104: Ensure Consistency In Multi Word Filters
### NetBox version

v4.0.1

### Feature type

Change to existing functionality

### Proposed functionality

Currently, in the User Interface, the models have Filter forms that are multi-word that are named like "Site group" but for the Side Navigation, multi word labels are capitalized to "Site Groups." This request is to ensure consistency in the filters.

### Use case

It would ensure consistent grammar without breaking any functionality. It's a minor change, but improves readability and ensures consistency throughout the entire program. Thus improving the user experience 

### Database changes

_No response_

### External dependencies

_No response_

### PR DESCRIPTION
**Pull request by danner26**
### Fixes: #16104 

Implement intentional capital filters rather than doing CSS capitalization. See [this PR](https://github.com/netbox-community/netbox/pull/16212) for reference

### CODE REVIEW

**Comment by danner26** [comment]
Sorry this is a big one!

**Comment by mr1716** [comment]
Related to [16104](https://github.com/netbox-community/netbox/issues/16104)

**Comment by danner26** [comment]
Fixed the link, thank you @mr1716

**Comment by mr1716** [comment]
@danner26 thanks for taking a look at this and creating a PR. Hoping this will be merged soon as this is a good improvement (low priority, but sadly something I can’t unsee) for the tool.

**Review by arthanson — APPROVED** [review]
@jeremystretch looks like just the label strings are changed here, however didn't know if the .po files should be changed in the PR - thinking they should get auto-updated?

**Comment by danner26** [comment]
If the translation files get auto-updated that would make this a lot easier. Please let me know if that is the case so I can remove those changes

**Comment by jeremystretch** [comment]
Who arbitrarily decided that the field labels all needed to use title case? Why are we modifying test data?

To be frank, there are currently [58 open bugs](https://github.com/netbox-community/netbox/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+bug%22), and this is not where we need to be spending time right now.

**Comment by mr1716** [comment]
@jeremystretch when the DCIM.Devices Filter Form has inconsistencies with wording such as Contact Group vs Tenant group and is inconsistent. I wanted to have my team use Netbox, but the feedback that I got was to fix this. This issue is can be found across all filter forms. It is a minor bug, that shouldnt theoretically be too hard to fix, but is noticeable.

image

**Comment by jeremystretch** [comment]
The scope of #16104 is simply to standardize the capitalization of form field labels, which, to be clear, is to _not_ use title case. (Only the first word needs to be capitalized.) Anything beyond this - filter sets, documentation, tests, etc. - is out of scope for the PR.

@danner26 it's up to you whether you want to greatly reduce the scope of these changes or leave it for someone else.

> I want to improve Netbox so it can be the best it can be.

This seems like an odd place to start, given there are so many issues with _much_ higher priority in need of an owner.

**Comment by mr1716** [comment]
> > I want to improve Netbox so it can be the best it can be.
> 
> This seems like an odd place to start, given there are so many issues with _much_ higher priority in need of an owner.

Just because it isn’t a high or medium priority item to fix, that doesn’t mean that it isn’t a legitimate issue that needs to be fixed. And that’s why I opened it, as an improvement is an improvement. Figured it’s a low hanging fruit item that I could use to help me understand how the Netbox tool works and how tickets are handled.

**Comment by jeremystretch** [comment]
@mr1716 every PR must be reviewed, and the time that I and the other maintainers have to spend on them is _extremely_ limited (hence the backlog of ~30 PRs currently). This is why we prioritize work with a substantial impact on the product. I've already spent more time on this issue than I can afford.

**Comment by mr1716** [comment]
> @mr1716 every PR must be reviewed, and the time that I and the other maintainers have to spend on them is _extremely_ limited (hence the backlog of ~30 PRs currently). This is why we prioritize work with a substantial impact on the product. I've already spent more time on this issue than I can afford.

Understood. I'm not asking this to be given a higher priority, nor pushed to the front, nor not reviewed, nor me given special priority. I know that your time is limited, every item has a different priority, and there are more important issues. I appreciate your time on this, as I never intended this to become a complex thing. Thought it was simply going to be "hey, let's decide on a specific standard for naming this stuff, and make a quick change to follow that standard." My apologies for taking your time.

**Comment by jeremystretch** [comment]
Closing this as the set of changes contained within is wildly out of scope for #16104.

**Comment by mr1716** [comment]
@jeremystretch the scope for is to ensure consistency in capitalization. I had put a bad title on it and have updated accordingly. My apologies for the confusions

**Pull request closed without merging**
