### PR TITLE
Add in in-line vlan editing and Bulk vlan editing

### LINKED ISSUE #2160: Bulk editing of interface VLAN assignments
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.3
* NetBox version:  2.3.3 

### Description

It would be nice if you could assign a VLAN to several interfaces at once.  When going to the device view and selecting several interfaces and edit them I can change description, mode, ... but it would be nice so set the VLAN  as well.

### LINKED ISSUE #3341: Move VLAN assignment to interface edit view from self-contained view
### Environment
* Python version:  3.6
* NetBox version:  2.6.1

### Proposed Functionality

This FR would result in moving the VLAN assignment page back into the main interface edit page.  Additionally, add in some JS magic to hide/clear and display those fields depending on whether the mode is Access, Trunk or None.

### Use Case

Currently, the VLAN edit interface is fairly bulky and unwieldy.  You are required go to another view in order to edit VLANs.  You are then required to save and return to the interface edit view.  

In addition to being unwieldy, this results in webhooks being fired for the interface model edit when just simply saving vlans (or if you have to switch from Access to Trunk)

### Database Changes

None

### External Dependencies

None

### Required Changes

* Remove Vlan panel
* Remove VLAN Assignment view/form
* Add 2 form fields for "Untagged VLAN" and "Tagged VLANs"
* Add in some JS Magic
* Add in validation

### PR DESCRIPTION
**Pull request by DanSheps**
### Fixes:

* Fixes: #3341 - Add in-line VLAN editing to the edit interface form 
* Fixes: #2160 - Add bulk editing of vlans

Consequential behaviour changes

* APISelect can now take "full=True" to return a non-brief set
* Select2 will no group by "group & site, group, site, global" if full=True is set in APISelect
* BulkEditView checks for QuerySet's and performs getattr().set() instead of setattr() for both regular data and nullified data

In order for this to work, had to check for a queryset being returned during the bulk edit and to use .set() instead of setattr.

### CODE REVIEW

**Comment by DanSheps** [comment]
If some brave souls want to do some QA testing:

https://dansheps.netbox.dansheps.com

**Comment by NannsIyam** [comment]
Congratulations for all the job done guys ! Netbox is amazingly useful !
I've noticed the possibility to ad a VLAN twice on the same interface : once tagged, once untagged.
You can check Eth1/1/7 on 'Test' device.

**Comment by lampwins** [comment]
@NannsIyam this is valid as multiple network vendors allow this to be done.

**Comment by NannsIyam** [comment]
Oops, yes, that's right.
I was confused compared with the actual interface which shows one line per VLAN.
I find the actual layout (one line/VLAN an chekboxes) more concise.

**Pull request merged**
