### PR TITLE
Implements #417 - Rack furniture (cable managers, shelves, blanks, etc.)

### LINKED ISSUE #417: Representation of cable managers, blanks, etc. in racks
It seems like this may fall within the realm of #20 or it may be too much scope creep for that particular ticket...

It would be nice to be able to place objects in a rack, such as cable managers, blanks, shelves, etc. Currently, I am creating a device for a _2U Horizontal Cable Manager_ and setting it to offline. Unfortunately, this means there is a new device created for every single cable manager.

The other option is I have completely missed where to perform this task (v1.4.0) and it is already included in the feature set.

IMO this wouldn't need to be anything more than an object, with options for '_label_', '_RU_', and '_color_'. Of course, we could also get as complicated as the imagination will allow, but it seems a bit unnecessary to make too much of it.

### PR DESCRIPTION
**Pull request by lampwins**
### Fixes: #417 

~~This implements two new dcim models `RackFurnitureType` and `RackFurniture`. They act much like `DeviceType` and `Device` where `RackFurnitureType` is a mix of `DeviceType` and `DeviceRole`. Also implements the api, docs and associated tests.~~

~~As discussed in the new docs in this PR, rack furniture allows modeling of "dumb" rackable items such as cable managers, shelves, blanks, etc. From a UI/UX perspective they act just like devices in the way they relate to racks except furniture _must_ be racked.~~

~~This modifies the rack utilization and validation logic to support both devices and furniture. A couple of new tests were added to verify that new logic is (mostly) sound. The rack elevations show both types and allows added both types from the rack elevation view.~~

This PR implements support for Rack Furniture and other "dump" rackable deviecs.

### CODE REVIEW

**Comment by danimo** [comment]
This is a very interesting feature, thanks! @lampwins, can you resolve the conflict?

**Comment by lampwins** [comment]
@danimo I have resolved the issues.

**Comment by lamiskin** [comment]
This would be a very handy feature to have. Any chance this could make it in to the next release?

**Comment by danimo** [comment]
@jeremystretch Can you clarify whether you would accept this feature before we ask @lampwins to resolve conflicts again?

**Comment by orbitalxox** [comment]
@lampwins @jeremystretch 
Hi,
Do you have some news pz? It's a must-have feature, i can't wait to see it in upcoming release! :)

**Comment by jasonyates** [comment]
Is this something that is still being considered? Right now I am handling "furniture" by adding reservations but this feature would be IDEAL before I make the push to roll this tool out to all of my remote sites.

**Comment by comnam90** [comment]
@jeremystretch @danimo 
Whats the go? Keen to see this make it in

**Comment by lampwins** [comment]
@jeremystretch I took this PR back to the drawing board and implemented it within the existing Device/DeviceType models. This PR now creates a new field `is_rack_furniture` on the `DeviceType` model. This field is ultimately used to suppresses functionality which is unrelated to rack furniture, throughout the application.

There is logic in all the various component/FK models' clean methods to ensure those model instances cannot be created and/or associated with a device with the rack furniture device type.

I also wrote some tests to cover this new model logic.

**Comment by lamiskin** [comment]
@jeremystretch Any progress in accepting this merge?

**Comment by kwilliams312** [comment]
I'm sad to see this died on the vine,  any change we could get the conflicts resolved @lampwins?  @jeremystretch Is this something we can get into the system?

**Comment by lampwins** [comment]
Closing this per the discussion in #417.

**Pull request closed without merging**
