### PR TITLE
Fixes #9108 & #8944 - Sanitize HTML after rendering markdown

### LINKED ISSUE #9108: Markdown syntax not working correctly within comment fields
### NetBox version

v3.2.0

### Python version

3.8

### Steps to Reproduce

1. Navigate to any object that has a 'comments' field.
2. Attempt to create a URL using angle brackets < >.
3. Click save.

### Expected Behavior

Netbox should turn the text within the angle brackets into a clickable URL.

### Observed Behavior

Text contained within the angle brackets completely disappears after clicking save.

### PR DESCRIPTION
**Pull request by kkthxbye-code**
### Fixes: #9108 and #8944

This PR removes the stripping of all HTML tags and the workarounds for sanitizing markdown links. Instead the HTML output of python-markdown is sanitized using [bleach](https://github.com/mozilla/bleach). The result is a more correct handling of markdown (HTML is explicitly allowed in the markdown spec) while still preventing user defined HTML that might result in XSS, by sanitizing with a whitelist approach.

From a little unscientific testing of a journal page with extreme markdown usage, the performance penalty is very slight (2-5% of total page load time).

I targeted this at the feature branch as a new dependency is added, not sure if that is correct. If it's not I'll change the target branch.

### CODE REVIEW

**Comment by kkthxbye-code** [comment]
Should also fix #8230 which was auto closed.

**Comment by jeremystretch** [comment]
Thanks for digging into this @kkthxbye-code! I had a feeling the eventual fallback to bleach was inevitable.

> I targeted this at the feature branch as a new dependency is added, not sure if that is correct. If it's not I'll change the target branch.

IMO it's fine to push this in the next patch release, since it's not a breaking change. I'll update the PR.

**Comment by kkthxbye-code** [comment]
I think it should be good now @jeremystretch - I'll never learn rebasing properly, always seems like a huge mess.

**Comment by jeremystretch** [comment]
git

**Pull request merged**
