### PR TITLE
Assign IP Address to Interface from Interface List and Add IP addresses to the interface list

### LINKED ISSUE #1001: request: Edit IP Address assignment on device overview page.
Would it be possible to when editing an IP Address assignment to an interface, that the interface can be changed without having to delete the assignment and re-create it on a different interface?

Also to add the edit icon next to the delete icon to allow for easy IP Address editing rather than having to click through using the IP Address.

### PR DESCRIPTION
**Pull request by snazy2000**
### Fixes: Partially Fixes #1001  and #878 

image

I've changed the connect and disconnect buttons to arrows as looked like Connecting and disconnecting a cable

I've also added the + which adds an IP address, could get rid of the IP address section if we added the delete button next to the IP Address?

I've had a good feedback from people I work with about the change

### CODE REVIEW

**Comment by snazy2000** [comment]
I have added the ability to edit the ip from within the device page, and made changes so that interface can be changed -https://github.com/digitalocean/netbox/pull/1040/commits/67ba5a59547ca6ed8d728e9dd9fd347c6384bb82

Fully Fixes #1001

**Comment by snazy2000** [comment]
Any comments on this / idea when may be pulled? :)

**Comment by jeremystretch** [comment]
We need to avoid mixing interfaces and IPs in the same table. It's confusing and artificially constrains the columns. I played around a bit with using Bootstrap rows, but couldn't come up with anything that looked good. Ideally, the interface and its IPs should all appear in a single row, similar to what candlerb proposes [here](https://github.com/digitalocean/netbox/issues/878#issuecomment-287303124). Just need to work out the markup.

**Comment by snazy2000** [comment]
I also had a play making like that but it didn't look right at all, as I was thinking that could remove the IP Address table fully and have all on the interfaces so against the IP Address there would be delete and edit next to it but i guess it may get bit over crowded

Can you part merge just the edit functionality as it is SUPER handy!!

**Comment by jeremystretch** [comment]
I tried a few different approach but ended up basically where you're at with the IP addresses. I'm going to close this PR because I'd rather handle #1001 separately, but this was my inspiration for d5c3f9e. Please comment on #878 with your thoughts. Thanks for your contribution!

**Pull request closed without merging**
