### PR TITLE
Adding a reference to deploying NetBox via Kubernetes manifests

### LINKED ISSUE #3496: Adding Kubernetes as an Alternative Installation option
### Change Type 
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
We've been running NetBox in production deployed on top of Kubernetes for a little while and we hope to contribute sample manifests that we've been using as templates that others can use.

### PR DESCRIPTION
**Pull request by mohahmed13**
### Fixes: #3496 

This pull request adds a reference to a repository with sample manifests for deploying NetBox on a Kubernetes cluster. The idea was to add it as an alternative installation method in the repo along with the other installation methods.

### CODE REVIEW

**Comment by kobayashi** [comment]
Travis CI shows 'extra line at netbox/dcim/forms.py:2334:1: E303 too many blank lines (3)'
That was fixed in commit https://github.com/netbox-community/netbox/commit/e8ee6f1bc5f5df89dc4a88a56f2d6384ca850d28
Could you checkout the latest for your branch and PR again?

**Comment by DanSheps** [comment]
I manually initiated another rebuild, it is passing now.

However, the attached issue has been closed so I will be closing this as well.

**Comment by mohahmed13** [comment]
@DanSheps , I had a discussion around this with @jeremystretch on slack regarding the issue. It was originally thought of as an edit to the main docs as opposed to the readme. He had suggested to open a PR once the repo was public. 

Let me know if you need me to open a new issue/PR to get this in.

**Comment by DanSheps** [comment]
Yeah, I am not sure what @jeremystretch has planned for this then.

**Comment by jeremystretch** [comment]
Sorry, I think I confused #3496 with something else related to Kubernetes. This should be fine.

**Pull request merged**
