### PR TITLE
Corrections in the examples in webhooks.md

### LINKED ISSUE #3600: Examples in webhooks.md need updating
### Change Type
[ ] Addition
[X ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

In webhooks.md, the POST request examples need adjusting:
- signal_received_timestamp -> timestamp, and the example format is incorrect
- username is missing
- request_id is missing

### PR DESCRIPTION
**Pull request by markkuleinio**
### Fixes: #3600

Adds username and request_id, changes signal_received_timestamp to timestamp, with changed format.

### CODE REVIEW

**Comment by markkuleinio** [comment]
I'm not sure if the PR looks right: 95 commits, but just one file changed (the one I edited)

**Comment by jeremystretch** [comment]
@markkuleinio can you rebase this off of the current `develop` branch please?

**Comment by markkuleinio** [comment]
@jeremystretch I just did my first-ever git rebase... :-/ How does it look like now?

**Comment by lampwins** [comment]
@markkuleinio The webhook changes look good, but what is the apache change? Generally, we would not want to mix those changes in the same PR.

**Comment by markkuleinio** [comment]
I don't know where did that come from. Let me know if you want me to close this PR and submit a new one.

**Comment by lampwins** [comment]
It is showing up as a reverted commit likely a result of your rebase I guess. Feel free to open a fresh PR if that is easier.

**Comment by markkuleinio** [comment]
Closing due to errors

**Pull request closed without merging**
